#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const readline = require('node:readline');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(PROJECT_ROOT, '.env');
const ENV_BACKUP_SUFFIX = '.wizard.bak';

const WIZARD_HEADER = [
	'========================================================',
	'  Cabros Bot — first-run operator setup',
	'========================================================',
	'',
	'This wizard will create a `.env` file with the minimum required',
	'configuration to send your first alert. All prompts are optional —',
	'press Enter to skip a section.',
	'',
].join('\n');

function parseArgs(argv) {
	const opts = { nonInteractive: false, minimal: false, help: false, dryRun: false };
	for (const arg of argv.slice(2)) {
		if (arg === '--non-interactive' || arg === '--non-interactive=true') opts.nonInteractive = true;
		else if (arg === '--minimal' || arg === '--minimal=true') opts.minimal = true;
		else if (arg === '--dry-run') opts.dryRun = true;
		else if (arg === '--help' || arg === '-h') opts.help = true;
	}
	return opts;
}

function printHelp() {
	process.stdout.write([
		'Usage: node scripts/setup-wizard.js [options]',
		'',
		'Options:',
		'  --non-interactive   Run without prompts (uses defaults)',
		'  --minimal           Minimal mode: only required keys',
		'  --dry-run           Print resolved env vars without writing .env',
		'  --help, -h          Show this help',
		'',
	].join('\n'));
}

function generateApiKey() {
	return crypto.randomBytes(32).toString('base64url');
}

function generateCallbackSecret() {
	return crypto.randomBytes(32).toString('base64url');
}

function parseExistingEnv(content) {
	const result = {};
	const lines = content.split(/\r?\n/);
	for (const line of lines) {
		if (!line || line.startsWith('#')) continue;
		const match = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
		if (!match) continue;
		const [, key, rawValue] = match;
		let value = rawValue;
		if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
			value = value.slice(1, -1);
		}
		result[key] = value;
	}
	return result;
}

function serializeEnv(entries) {
	const lines = [
		'# Generated by scripts/setup-wizard.js',
		`# Generated at ${new Date().toISOString()}`,
		'',
	];
	for (const [key, value] of entries) {
		const needsQuotes = /[\s#"'=]/.test(String(value));
		const formatted = needsQuotes ? `"${String(value).replace(/"/g, '\\"')}"` : value;
		lines.push(`${key}=${formatted}`);
	}
	lines.push('');
	return lines.join('\n');
}

function diffEnvKeys(existing, next) {
	const added = [];
	const changed = [];
	const nextEntries = next instanceof Map ? next : Object.entries(next);
	const iterable = next instanceof Map
		? next.entries()
		: nextEntries;
	for (const [key, value] of iterable) {
		if (!(key in existing)) added.push(key);
		else if (existing[key] !== value) changed.push(key);
	}
	return { added, changed };
}

function backupEnv(targetPath) {
	if (!fs.existsSync(targetPath)) return null;
	const backupPath = `${targetPath}${ENV_BACKUP_SUFFIX}`;
	let suffix = 1;
	let finalPath = backupPath;
	while (fs.existsSync(finalPath)) {
		suffix += 1;
		finalPath = `${backupPath}.${suffix}`;
	}
	fs.copyFileSync(targetPath, finalPath);
	return finalPath;
}

function createPrompt() {
	const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
	return {
		rl,
		ask(question, { defaultValue = '' } = {}) {
			return new Promise((resolve) => {
				const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
				rl.question(prompt, (answer) => resolve(answer));
			});
		},
		close() { rl.close(); },
	};
}

async function collectInteractiveAnswers(existingEnv, prompt) {
	const answers = {};
	if (!('BOT_TOKEN' in existingEnv)) {
		const v = await prompt.ask('Telegram BOT_TOKEN (get it from @BotFather)');
		if (v) answers.BOT_TOKEN = v;
	}
	if (!('TELEGRAM_CHAT_ID' in existingEnv)) {
		const v = await prompt.ask('Telegram TELEGRAM_CHAT_ID (use /start to discover)');
		if (v) answers.TELEGRAM_CHAT_ID = v;
	}
	if (!('WEBHOOK_API_KEY' in existingEnv)) {
		const generated = generateApiKey();
		process.stdout.write(`\nGenerated WEBHOOK_API_KEY (printed once, copy now):\n  ${generated}\n\n`);
		const confirm = await prompt.ask('Press Enter to write this key, or type "skip" to omit');
		if (confirm !== 'skip') answers.WEBHOOK_API_KEY = generated;
	}
	if (!('JOB_CALLBACK_SIGNING_SECRET' in existingEnv)) {
		const generated = generateCallbackSecret();
		process.stdout.write(`\nGenerated JOB_CALLBACK_SIGNING_SECRET (printed once, copy now):\n  ${generated}\n\n`);
		const confirm = await prompt.ask('Press Enter to write this secret, or type "skip" to omit');
		if (confirm !== 'skip') answers.JOB_CALLBACK_SIGNING_SECRET = generated;
	}
	if (!('ENABLE_WHATSAPP_ALERTS' in existingEnv)) {
		const want = await prompt.ask('Enable WhatsApp alerts via GreenAPI? (y/N)');
		if (want && /^y(es)?$/i.test(want)) {
			answers.ENABLE_WHATSAPP_ALERTS = 'true';
			if (!('WHATSAPP_API_URL' in existingEnv)) {
				const url = await prompt.ask('GreenAPI base URL', { defaultValue: 'https://api.green-api.com' });
				if (url) answers.WHATSAPP_API_URL = url;
			}
			if (!('WHATSAPP_API_KEY' in existingEnv)) {
				const key = await prompt.ask('GreenAPI API key');
				if (key) answers.WHATSAPP_API_KEY = key;
			}
			if (!('WHATSAPP_CHAT_ID' in existingEnv)) {
				const chat = await prompt.ask('WhatsApp chat ID (e.g. 120363xxx@g.us)');
				if (chat) answers.WHATSAPP_CHAT_ID = chat;
			}
		}
	}
	return answers;
}

function resolveMinimalAnswers() {
	return {
		WEBHOOK_API_KEY: generateApiKey(),
		JOB_CALLBACK_SIGNING_SECRET: generateCallbackSecret(),
		ENABLE_TELEGRAM_BOT: 'false',
	};
}

async function runWizard(opts) {
	if (opts.help) { printHelp(); return 0; }
	process.stdout.write(WIZARD_HEADER);

	let existingEnv = {};
	if (fs.existsSync(ENV_PATH)) {
		process.stdout.write(`Existing .env detected at ${ENV_PATH}\n`);
		existingEnv = parseExistingEnv(fs.readFileSync(ENV_PATH, 'utf8'));
		process.stdout.write(`  → ${Object.keys(existingEnv).length} keys preserved\n\n`);
	}

	let nextEntries;
	if (opts.nonInteractive && opts.minimal) {
		nextEntries = { ...existingEnv, ...resolveMinimalAnswers() };
		process.stdout.write('Generated minimal non-interactive .env content:\n');
	} else if (opts.nonInteractive) {
		nextEntries = { ...existingEnv };
		process.stdout.write('Non-interactive mode without --minimal writes no new keys.\n');
	} else {
		const prompt = createPrompt();
		try {
			const answers = await collectInteractiveAnswers(existingEnv, prompt);
			nextEntries = { ...existingEnv, ...answers };
		} finally {
			prompt.close();
		}
	}

	const orderedEntries = Object.entries(nextEntries).sort(([a], [b]) => a.localeCompare(b));
	const { added, changed } = diffEnvKeys(existingEnv, Object.fromEntries(orderedEntries));

	process.stdout.write('\nPlanned .env changes:\n');
	if (added.length === 0 && changed.length === 0) {
		process.stdout.write('  (none — your existing .env is already complete)\n');
	} else {
		for (const k of added) process.stdout.write(`  + ${k}\n`);
		for (const k of changed) process.stdout.write(`  ~ ${k}\n`);
	}

	if (opts.dryRun) {
		process.stdout.write('\nDry-run requested; .env not written.\n');
		return 0;
	}

	if (fs.existsSync(ENV_PATH)) {
		const backup = backupEnv(ENV_PATH);
		if (backup) process.stdout.write(`\nBacked up existing .env → ${backup}\n`);
	}
	fs.writeFileSync(ENV_PATH, serializeEnv(orderedEntries), 'utf8');
	process.stdout.write(`\nWrote ${orderedEntries.length} keys to ${ENV_PATH}\n`);
	process.stdout.write('\nNext steps:\n');
	process.stdout.write('  1. Run `pnpm run doctor` to validate the resulting config.\n');
	process.stdout.write('  2. Run `pnpm run wizard:test` to smoke-test /healthcheck and /api/status.\n');
	process.stdout.write('  3. Run `pnpm start` to boot the bot.\n');
	return 0;
}

if (require.main === module) {
	const opts = parseArgs(process.argv);
	runWizard(opts).then((code) => process.exit(code ?? 0)).catch((error) => {
		process.stderr.write(`wizard failed: ${error && error.message ? error.message : error}\n`);
		process.exit(1);
	});
}

module.exports = {
	parseArgs,
	parseExistingEnv,
	serializeEnv,
	generateApiKey,
	generateCallbackSecret,
	diffEnvKeys,
	backupEnv,
	resolveMinimalAnswers,
	runWizard,
	REQUIRED_KEYS: ['WEBHOOK_API_KEY'],
};