'use strict';

/**
 * AlertStorageService — stores webhook alert documents in Cloud Firestore.
 *
 * Initialization pattern is copied from branch 006-csv-gemini-signals
 * (src/services/csvSignals/firestoreRepository.js):
 *   - Lazy singleton via admin.initializeApp() / admin.firestore()
 *   - Feature-gated: ENABLE_FIRESTORE_ALERT_STORAGE=true required
 *   - Fail-open: any Firestore error is caught and logged as a warning;
 *     the alert delivery flow is never blocked or failed by storage errors.
 *
 * Collection: alerts
 * Document ID: auto-generated by Firestore (collection.add())
 *
 * Document schema:
 *   receivedAt       - FieldValue.serverTimestamp()
 *   text             - string  — original alert text
 *   enriched         - boolean — whether enrichment ran
 *   enrichmentData   - object | null — alert.enriched payload
 *   tokenUsage       - object | null — tokenUsage.toJSON() result
 *   deliveryResults  - array  — per-channel SendResult objects
 *   source           - string — always "webhook"
 *   useTradingViewData - boolean — query param from the request
 */

const admin = require('firebase-admin');
const { encodeAlertPaginationCursor, parseAlertPaginationCursor } = require('./alertPaginationCursor');

const COLLECTION_NAME = 'alerts';
const REPLAY_COLLECTION_NAME = 'alertReplays';
const DEFAULT_PAGE_SIZE = 50;
const MAX_PAGE_SIZE = 100;
const DEFAULT_SUMMARY_LIMIT = 500;
const MAX_SUMMARY_LIMIT = 1000;
const MAX_SUMMARY_WINDOW_DAYS = 31;
const DEFAULT_EXPORT_LIMIT = 500;
const MAX_EXPORT_LIMIT = 1000;
const MAX_EXPORT_WINDOW_DAYS = 31;
const MAX_EXPORT_TEXT_LENGTH = 1000;
const STORAGE_UNAVAILABLE_CODE = 'STORAGE_UNAVAILABLE';
const INVALID_CURSOR_MESSAGE = 'Invalid before cursor. Use an ISO-8601 timestamp or the nextBefore cursor from a previous response.';

// Lazy Firestore singleton
let db = null;

function isEnabled() {
	return process.env.ENABLE_FIRESTORE_ALERT_STORAGE === 'true';
}

function canInitializeFirestore() {
	return isEnabled() || process.env.ENABLE_FIRESTORE_JOB_STORAGE === 'true';
}

function clampLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_PAGE_SIZE;
	}

	return Math.min(limit, MAX_PAGE_SIZE);
}

function getDocTimestamp(document) {
	if (!document || !document.receivedAt || typeof document.receivedAt.toDate !== 'function') {
		return null;
	}

	return document.receivedAt.toDate().toISOString();
}

function formatAlertDocument(doc) {
	const data = doc.data() || {};
	return {
		id: doc.id,
		receivedAt: getDocTimestamp(data),
		text: typeof data.text === 'string' ? data.text : '',
		enriched: Boolean(data.enriched),
		enrichmentData: data.enrichmentData || null,
		tokenUsage: data.tokenUsage || null,
		deliveryResults: Array.isArray(data.deliveryResults) ? data.deliveryResults : [],
		source: typeof data.source === 'string' ? data.source : null,
		useTradingViewData: Boolean(data.useTradingViewData),
	};
}

function getNumericValue(value) {
	const numeric = Number(value);
	return Number.isFinite(numeric) ? numeric : 0;
}

function incrementCounter(target, key) {
	const normalizedKey = typeof key === 'string' && key.trim()
		? key.trim()
		: 'unknown';
	target[normalizedKey] = (target[normalizedKey] || 0) + 1;
}

function extractAlertSymbol(data) {
	const candidates = [
		data.symbol,
		data.ticker,
		data.enrichmentData && data.enrichmentData.symbol,
		data.enrichmentData && data.enrichmentData.ticker,
		data.enrichmentData && data.enrichmentData.asset,
		data.enrichmentData && data.enrichmentData.original_symbol,
	];

	const symbol = candidates.find((candidate) => typeof candidate === 'string' && candidate.trim());
	return symbol ? symbol.trim().toUpperCase() : 'unknown';
}

function addTokenUsage(totals, tokenUsage) {
	if (!tokenUsage || typeof tokenUsage !== 'object') {
		return;
	}

	totals.inputTokens += getNumericValue(tokenUsage.inputTokens || tokenUsage.promptTokens);
	totals.outputTokens += getNumericValue(tokenUsage.outputTokens || tokenUsage.completionTokens);
	totals.totalTokens += getNumericValue(tokenUsage.totalTokens || tokenUsage.total);
	totals.totalCost += getNumericValue(tokenUsage.totalCost);
}

function addDeliverySummary(summary, deliveryResults) {
	if (!Array.isArray(deliveryResults)) {
		return;
	}

	for (const result of deliveryResults) {
		if (!result || typeof result !== 'object') {
			continue;
		}

		const channel = typeof result.channel === 'string' && result.channel.trim()
			? result.channel.trim()
			: 'unknown';
		if (!summary.byChannel[channel]) {
			summary.byChannel[channel] = { total: 0, success: 0, failure: 0 };
		}

		summary.byChannel[channel].total += 1;
		if (result.success) {
			summary.byChannel[channel].success += 1;
			summary.totalSuccess += 1;
		} else {
			summary.byChannel[channel].failure += 1;
			summary.totalFailure += 1;
		}
	}
}

function summarizeDeliveryResults(deliveryResults) {
	if (!Array.isArray(deliveryResults)) {
		return [];
	}

	return deliveryResults.map((result) => ({
		channel: typeof result.channel === 'string' ? result.channel : null,
		success: Boolean(result.success),
		messageId: typeof result.messageId === 'string' ? result.messageId : null,
		errorCode: typeof result.errorCode === 'string' ? result.errorCode : null,
		statusCode: Number.isInteger(result.statusCode) ? result.statusCode : null,
	})).filter(result => result.channel);
}

function summarizeTokenUsage(tokenUsage) {
	if (!tokenUsage || typeof tokenUsage !== 'object') {
		return null;
	}

	return {
		inputTokens: getNumericValue(tokenUsage.inputTokens || tokenUsage.promptTokens),
		outputTokens: getNumericValue(tokenUsage.outputTokens || tokenUsage.completionTokens),
		totalTokens: getNumericValue(tokenUsage.totalTokens || tokenUsage.total),
		totalCost: getNumericValue(tokenUsage.totalCost),
	};
}

function truncateAlertText(text) {
	if (typeof text !== 'string') {
		return '';
	}

	return text.length > MAX_EXPORT_TEXT_LENGTH
		? text.substring(0, MAX_EXPORT_TEXT_LENGTH)
		: text;
}

function formatExportRecord(doc, { includeText }) {
	const data = doc.data() || {};
	const record = {
		id: doc.id,
		receivedAt: getDocTimestamp(data),
		source: typeof data.source === 'string' ? data.source : null,
		enriched: Boolean(data.enriched),
		useTradingViewData: Boolean(data.useTradingViewData),
		deliveryResults: summarizeDeliveryResults(data.deliveryResults),
		tokenUsage: summarizeTokenUsage(data.tokenUsage),
	};

	if (includeText) {
		record.text = truncateAlertText(data.text);
	}

	return record;
}

function collectLatency(samples, value) {
	const numeric = Number(value);
	if (Number.isFinite(numeric) && numeric >= 0) {
		samples.push(numeric);
	}
}

function averageLatency(samples) {
	if (samples.length === 0) {
		return null;
	}

	return Math.round(samples.reduce((sum, value) => sum + value, 0) / samples.length);
}

function buildSummaryWindow({ from, to, limit }) {
	const now = new Date();
	const parsedTo = to ? new Date(to) : now;
	const maxWindowMs = MAX_SUMMARY_WINDOW_DAYS * 24 * 60 * 60 * 1000;
	let parsedFrom = from ? new Date(from) : new Date(parsedTo.getTime() - (24 * 60 * 60 * 1000));

	if (parsedTo.getTime() - parsedFrom.getTime() > maxWindowMs) {
		parsedFrom = new Date(parsedTo.getTime() - maxWindowMs);
	}

	if (parsedFrom.getTime() > parsedTo.getTime()) {
		const error = new Error('Invalid summary window. from must be before or equal to to.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	return {
		from: parsedFrom.toISOString(),
		to: parsedTo.toISOString(),
		limit: clampSummaryLimit(limit),
		maxDays: MAX_SUMMARY_WINDOW_DAYS,
	};
}

function buildExportWindow({ from, to, limit }) {
	if (!from || !to) {
		const error = new Error('Export requests require bounded from and to ISO-8601 timestamps.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	const parsedFrom = new Date(from);
	const parsedTo = new Date(to);
	const maxWindowMs = MAX_EXPORT_WINDOW_DAYS * 24 * 60 * 60 * 1000;

	if (parsedFrom.getTime() > parsedTo.getTime()) {
		const error = new Error('Invalid export window. from must be before or equal to to.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	if (parsedTo.getTime() - parsedFrom.getTime() > maxWindowMs) {
		const error = new Error(`Invalid export window. Maximum export window is ${MAX_EXPORT_WINDOW_DAYS} days.`);
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	return {
		from: parsedFrom.toISOString(),
		to: parsedTo.toISOString(),
		limit: clampExportLimit(limit),
		maxDays: MAX_EXPORT_WINDOW_DAYS,
	};
}

function clampSummaryLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_SUMMARY_LIMIT;
	}

	return Math.min(limit, MAX_SUMMARY_LIMIT);
}

function clampExportLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_EXPORT_LIMIT;
	}

	return Math.min(limit, MAX_EXPORT_LIMIT);
}

function matchesFilters(alert, filters) {
	if (filters.source && alert.source !== filters.source) {
		return false;
	}

	if (typeof filters.enriched === 'boolean' && alert.enriched !== filters.enriched) {
		return false;
	}

	return true;
}

function createStorageUnavailableError(cause) {
	const error = new Error('Alert storage is enabled but Firestore is unavailable. Check Firestore credentials and project configuration.');
	error.code = STORAGE_UNAVAILABLE_CODE;
	if (cause) {
		error.cause = cause;
	}
	return error;
}

function createInvalidCursorError() {
	const error = new Error(INVALID_CURSOR_MESSAGE);
	error.code = 'INVALID_REQUEST';
	return error;
}

function buildParsedCursorTimestamp(parsedCursor) {
	return admin.firestore.Timestamp.fromDate(new Date(parsedCursor.receivedAt));
}

function getDocCursorValues(doc) {
	if (!doc || typeof doc.data !== 'function') {
		return null;
	}

	const data = doc.data() || {};
	const receivedAt = getDocTimestamp(data);
	if (!receivedAt || typeof doc.id !== 'string' || !doc.id) {
		return null;
	}

	return {
		receivedAt,
		documentId: doc.id,
	};
}

/**
 * Initialize Firebase Admin (idempotent) and return Firestore client.
 * Returns null when the feature is disabled or initialization fails.
 *
 * Credential resolution order (matches firebase-admin defaults):
 *   1. GOOGLE_APPLICATION_CREDENTIALS env var (path to service-account JSON file)
 *   2. FIREBASE_SERVICE_ACCOUNT_JSON env var   (inline JSON string, preferred for Render secrets)
 *   3. Application Default Credentials          (GCP / Cloud Run managed identity)
 *
 * @returns {FirebaseFirestore.Firestore | null}
 */
function getFirestore() {
	if (!canInitializeFirestore()) {
		return null;
	}

	if (db) {
		return db;
	}

	try {
		let credential;

		// Option B: inline JSON (preferred for Render.com secret env vars)
		if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
			const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
			credential = admin.credential.cert(serviceAccount);
		}
		// Option A: GOOGLE_APPLICATION_CREDENTIALS file path handled automatically by initializeApp()

		const appOptions = {};
		if (credential) {
			appOptions.credential = credential;
		}
		if (process.env.FIREBASE_PROJECT_ID) {
			appOptions.projectId = process.env.FIREBASE_PROJECT_ID;
		}

		if (!admin.apps.length) {
			admin.initializeApp(appOptions);
		}

		db = admin.firestore();
		console.debug('[AlertStorageService] Firestore client initialized');
	} catch (error) {
		console.warn('[AlertStorageService] Failed to initialize Firestore client:', error.message);
		db = null;
	}

	return db;
}

/**
 * Persist a webhook alert document to the `alerts` Firestore collection.
 *
 * This is designed to be called fire-and-forget from the alert handler.
 * All errors are caught internally — this method never throws.
 *
 * @param {Object} params
 * @param {string}  params.text              - Original alert text
 * @param {boolean} params.enriched          - Whether enrichment ran
 * @param {Object|null} params.enrichmentData - alert.enriched object or null
 * @param {Object|null} params.tokenUsage    - tokenUsage.toJSON() result or null
 * @param {Array}   params.deliveryResults   - Array of SendResult from notificationManager.sendToAll()
 * @param {boolean} params.useTradingViewData - Whether ?useTradingViewData=true was set on the request
 * @returns {Promise<string|null>} The new Firestore document ID, or null on failure/disabled
 */
async function saveAlert({ text, enriched, enrichmentData, tokenUsage, deliveryResults, useTradingViewData }) {
	const firestore = getFirestore();
	if (!firestore) {
		return null;
	}

	try {
		const document = {
			receivedAt: admin.firestore.FieldValue.serverTimestamp(),
			text: typeof text === 'string' ? text.substring(0, 20000) : '',
			enriched: Boolean(enriched),
			enrichmentData: enrichmentData || null,
			tokenUsage: tokenUsage || null,
			deliveryResults: Array.isArray(deliveryResults) ? deliveryResults : [],
			source: 'webhook',
			useTradingViewData: Boolean(useTradingViewData),
		};

		const docRef = await firestore.collection(COLLECTION_NAME).add(document);
		console.debug(`[AlertStorageService] Alert stored with ID: ${docRef.id}`);
		return docRef.id;
	} catch (error) {
		console.warn('[AlertStorageService] Failed to store alert in Firestore:', error.message);
		return null;
	}
}

/**
 * Read stored alerts from Firestore with a descending receivedAt cursor.
 *
 * Filtering stays in memory so the endpoint does not require new composite
 * Firestore indexes for source/enriched combinations.
 *
 * @param {Object} params
 * @param {number} params.limit
 * @param {string|undefined} params.before
 * @param {string|undefined} params.source
 * @param {boolean|undefined} params.enriched
 * @returns {Promise<{alerts: Array, hasMore: boolean, nextBefore: string|null}|null>}
 */
async function listAlerts({ limit = DEFAULT_PAGE_SIZE, before, source, enriched } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const pageSize = clampLimit(limit);
	const targetCount = pageSize + 1;
	const matches = [];
	const parsedBeforeCursor = before
		? parseAlertPaginationCursor(before)
		: null;
	if (before && !parsedBeforeCursor) {
		throw createInvalidCursorError();
	}

	let pageCursor = parsedBeforeCursor
		? {
			receivedAt: parsedBeforeCursor.receivedAt,
			documentId: parsedBeforeCursor.documentId,
		}
		: null;

	while (matches.length < targetCount) {
		let query = firestore
			.collection(COLLECTION_NAME)
			.orderBy('receivedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc')
			.limit(targetCount);
		if (pageCursor) {
			const cursorTimestamp = buildParsedCursorTimestamp(pageCursor);
			if (pageCursor.documentId) {
				query = query.startAfter(cursorTimestamp, pageCursor.documentId);
			} else {
				query = query.where('receivedAt', '<', cursorTimestamp);
			}
		}

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to read alerts from Firestore:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || snapshot.empty || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			break;
		}

		for (const doc of snapshot.docs) {
			const formatted = formatAlertDocument(doc);
			if (matchesFilters(formatted, { source, enriched })) {
				matches.push(formatted);
				if (matches.length >= targetCount) {
					break;
				}
			}
		}

		const lastDocCursor = getDocCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!lastDocCursor) {
			break;
		}

		pageCursor = lastDocCursor;
		if (snapshot.docs.length < targetCount) {
			break;
		}
	}

	const alerts = matches.slice(0, pageSize);
	return {
		alerts,
		hasMore: matches.length > pageSize,
		nextBefore: alerts.length > 0
			? encodeAlertPaginationCursor(alerts[alerts.length - 1])
			: null,
	};
}

/**
 * Fetch a single stored alert by its Firestore document ID.
 *
 * @param {string} alertId
 * @returns {Promise<Object|null>}
 */
async function getAlertById(alertId) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	let snapshot;
	try {
		snapshot = await firestore.collection(COLLECTION_NAME).doc(alertId).get();
	} catch (error) {
		console.warn('[AlertStorageService] Failed to read alert from Firestore:', error.message);
		throw createStorageUnavailableError(error);
	}
	if (!snapshot || !snapshot.exists) {
		return null;
	}

	return formatAlertDocument(snapshot);
}

/**
 * Persist a replay attempt separately from the immutable original alert.
 *
 * @param {Object} params
 * @param {string} params.alertId
 * @param {string} params.idempotencyKey
 * @param {Array<string>} params.channels
 * @param {Array} params.deliveryResults
 * @returns {Promise<string|null>}
 */
async function saveReplayAttempt({ alertId, idempotencyKey, channels, deliveryResults }) {
	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const replayId = `${alertId}_${idempotencyKey}`;
	const document = {
		alertId,
		idempotencyKey,
		channels: Array.isArray(channels) ? channels : [],
		deliveryResults: Array.isArray(deliveryResults) ? deliveryResults : [],
		replayedAt: admin.firestore.FieldValue.serverTimestamp(),
		source: 'alert-replay',
	};

	try {
		await firestore.collection(REPLAY_COLLECTION_NAME).doc(replayId).set(document, { merge: false });
		return replayId;
	} catch (error) {
		console.warn('[AlertStorageService] Failed to store alert replay attempt:', error.message);
		throw createStorageUnavailableError(error);
	}
}

/**
 * Export a bounded set of stored alerts using safe, stable fields only.
 *
 * @param {Object} params
 * @param {string} params.from ISO timestamp, required
 * @param {string} params.to ISO timestamp, required
 * @param {number|undefined} params.limit Maximum documents returned, capped at 1000
 * @param {string|undefined} params.source Optional exact source filter
 * @param {boolean|undefined} params.enriched Optional enriched/plain filter
 * @param {boolean|undefined} params.includeText Include truncated alert text when true
 * @returns {Promise<{window: Object, alerts: Array}>}
 */
async function exportAlerts({ from, to, limit, source, enriched, includeText = false } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const window = buildExportWindow({ from, to, limit });
	let snapshot;
	try {
		snapshot = await firestore
			.collection(COLLECTION_NAME)
			.where('receivedAt', '>=', admin.firestore.Timestamp.fromDate(new Date(window.from)))
			.where('receivedAt', '<=', admin.firestore.Timestamp.fromDate(new Date(window.to)))
			.orderBy('receivedAt', 'desc')
			.limit(window.limit)
			.get();
	} catch (error) {
		console.warn('[AlertStorageService] Failed to export alerts from Firestore:', error.message);
		throw createStorageUnavailableError(error);
	}

	const docs = snapshot && Array.isArray(snapshot.docs) ? snapshot.docs : [];
	const alerts = docs
		.map(doc => formatExportRecord(doc, { includeText }))
		.filter(alert => matchesFilters(alert, { source, enriched }));

	return {
		window,
		alerts,
	};
}

/**
 * Build bounded aggregate metrics for stored alerts.
 *
 * The endpoint intentionally returns counts and totals only. Raw alert text,
 * provider payloads, credentials, and error details stay out of the response.
 *
 * @param {Object} params
 * @param {string|undefined} params.from ISO timestamp, defaults to 24h before to
 * @param {string|undefined} params.to ISO timestamp, defaults to now
 * @param {number|undefined} params.limit Maximum documents scanned, capped at 1000
 * @returns {Promise<Object|null>}
 */
async function summarizeAlerts({ from, to, limit } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const window = buildSummaryWindow({ from, to, limit });
	let snapshot;
	try {
		snapshot = await firestore
			.collection(COLLECTION_NAME)
			.where('receivedAt', '>=', admin.firestore.Timestamp.fromDate(new Date(window.from)))
			.where('receivedAt', '<=', admin.firestore.Timestamp.fromDate(new Date(window.to)))
			.orderBy('receivedAt', 'desc')
			.limit(window.limit)
			.get();
	} catch (error) {
		console.warn('[AlertStorageService] Failed to summarize alerts from Firestore:', error.message);
		throw createStorageUnavailableError(error);
	}

	const summary = {
		window,
		totalAlerts: 0,
		bySource: {},
		bySymbol: {},
		byFeatureFlag: {
			enriched: 0,
			plain: 0,
			tradingViewData: 0,
			withoutTradingViewData: 0,
		},
		enrichment: {
			enrichedAlerts: 0,
			plainAlerts: 0,
			tokenUsage: {
				inputTokens: 0,
				outputTokens: 0,
				totalTokens: 0,
				totalCost: 0,
			},
		},
		delivery: {
			totalSuccess: 0,
			totalFailure: 0,
			byChannel: {},
		},
		latency: {
			averageProcessingMs: null,
			averageDeliveryMs: null,
		},
	};
	const processingLatencySamples = [];
	const deliveryLatencySamples = [];

	const docs = snapshot && Array.isArray(snapshot.docs) ? snapshot.docs : [];
	for (const doc of docs) {
		const data = doc.data() || {};
		const enriched = Boolean(data.enriched);
		const useTradingViewData = Boolean(data.useTradingViewData);

		summary.totalAlerts += 1;
		incrementCounter(summary.bySource, data.source);
		incrementCounter(summary.bySymbol, extractAlertSymbol(data));

		if (enriched) {
			summary.byFeatureFlag.enriched += 1;
			summary.enrichment.enrichedAlerts += 1;
		} else {
			summary.byFeatureFlag.plain += 1;
			summary.enrichment.plainAlerts += 1;
		}

		if (useTradingViewData) {
			summary.byFeatureFlag.tradingViewData += 1;
		} else {
			summary.byFeatureFlag.withoutTradingViewData += 1;
		}

		addTokenUsage(summary.enrichment.tokenUsage, data.tokenUsage);
		addDeliverySummary(summary.delivery, data.deliveryResults);
		collectLatency(processingLatencySamples, data.processingTimeMs || data.processing_time_ms);

		if (Array.isArray(data.deliveryResults)) {
			for (const result of data.deliveryResults) {
				collectLatency(deliveryLatencySamples, result && (result.latencyMs || result.deliveryLatencyMs || result.durationMs));
			}
		}
	}

	summary.enrichment.tokenUsage.totalCost = Number(summary.enrichment.tokenUsage.totalCost.toFixed(6));
	summary.latency.averageProcessingMs = averageLatency(processingLatencySamples);
	summary.latency.averageDeliveryMs = averageLatency(deliveryLatencySamples);

	return summary;
}

module.exports = {
	isEnabled,
	saveAlert,
	listAlerts,
	getAlertById,
	summarizeAlerts,
	exportAlerts,
	saveReplayAttempt,
	STORAGE_UNAVAILABLE_CODE,
	INVALID_CURSOR_MESSAGE,
	parseAlertPaginationCursor,
	// Exported for testing
	getFirestore,
	COLLECTION_NAME,
	REPLAY_COLLECTION_NAME,
	// Reset the cached db singleton between tests without module reloading
	_resetForTesting() {
		db = null;
	},
};
