'use strict';

/**
 * AlertStorageService — stores webhook alert documents in Cloud Firestore.
 *
 * Initialization pattern is copied from branch 006-csv-gemini-signals
 * (src/services/csvSignals/firestoreRepository.js):
 *   - Lazy singleton via admin.initializeApp() / admin.firestore()
 *   - Feature-gated: an enabled storage consumer must be configured
 *   - Fail-open: any Firestore error is caught and logged as a warning;
 *     the alert delivery flow is never blocked or failed by storage errors.
 *
 * Collection: alerts
 * Document ID: auto-generated by Firestore (collection.add())
 *
 * Document schema:
 *   receivedAt       - FieldValue.serverTimestamp()
 *   expiresAt        - Timestamp — receivedAt + ALERT_STORAGE_RETENTION_DAYS
 *   text             - string  — original alert text
 *   enriched         - boolean — whether enrichment ran
 *   enrichmentData   - object | null — alert.enriched payload
 *   tokenUsage       - object | null — tokenUsage.toJSON() result
 *   deliveryResults  - array  — per-channel SendResult objects
 *   source           - string — always "webhook"
 *   useTradingViewData - boolean — query param from the request
 *   processingTimeMs - integer — bounded handler processing duration
 */

const admin = require('firebase-admin');
const crypto = require('crypto');
const { encodeAlertPaginationCursor, parseAlertPaginationCursor } = require('./alertPaginationCursor');
const { trackBackgroundTask } = require('../../lib/backgroundTaskTracker');

const COLLECTION_NAME = 'alerts';
const REPLAY_COLLECTION_NAME = 'alertReplays';
const DEFAULT_PAGE_SIZE = 50;
const MAX_PAGE_SIZE = 100;
const DEFAULT_SUMMARY_LIMIT = 500;
const MAX_SUMMARY_LIMIT = 1000;
const MAX_SUMMARY_WINDOW_DAYS = 31;
const DEFAULT_EXPORT_LIMIT = 500;
const MAX_EXPORT_LIMIT = 1000;
const MAX_EXPORT_WINDOW_DAYS = 31;
const MAX_EXPORT_TEXT_LENGTH = 1000;
// Stored alert text cap; high-volume expanded-analysis (50 symbols) and ranked
// market-scanner reports can exceed this. When clipped, the document is flagged
// with `truncated: true` and `originalLength` so consumers and replay can
// detect the loss; raise only if Firestore's 1 MiB document cap and the
// existing per-channel chunked delivery can absorb the full text.
const MAX_ALERT_TEXT_LENGTH = 20000;
const DEFAULT_ALERT_STORAGE_RETENTION_DAYS = 90;
const MAX_ALERT_STORAGE_RETENTION_DAYS = 3650;
const DAY_MS = 24 * 60 * 60 * 1000;
// ponytail: 24h ceiling rejects stuck-request outliers; raise only with observed legitimate longer handlers.
const MAX_PROCESSING_TIME_MS = 24 * 60 * 60 * 1000;
const STORAGE_UNAVAILABLE_CODE = 'STORAGE_UNAVAILABLE';
const INVALID_CURSOR_MESSAGE = 'Invalid before cursor. Use an ISO-8601 timestamp or the nextBefore cursor from a previous response.';
const RISK_METADATA_FIELDS = [
	'invalidation_level',
	'target_level',
	'setup_type',
	'risk_reward_ratio',
];
const VALID_SETUP_TYPES = new Set([
	'breakout',
	'mean_reversion',
	'trend_continuation',
	'reversal',
]);
const VALID_TRADINGVIEW_ENRICHMENT_STATUSES = new Set(['full', 'partial', 'failed', 'not_applicable']);

// Lazy Firestore singleton
let db = null;
let lastRetentionWarningValue = null;

function isEnabled() {
	return process.env.ENABLE_FIRESTORE_ALERT_STORAGE === 'true';
}

function canInitializeFirestore() {
	return isEnabled()
		|| process.env.ENABLE_FIRESTORE_SCANNER_PRESETS === 'true'
		|| process.env.ENABLE_FIRESTORE_JOB_STORAGE === 'true'
		|| process.env.ENABLE_SIGNAL_OUTCOME_TRACKING === 'true'
		|| process.env.ENABLE_FIREBASE_REMOTE_CONFIG === 'true'
		|| process.env.ENABLE_NOTIFICATION_REDRIVE === 'true'
		|| process.env.ENABLE_NEWS_MONITOR_SCHEDULER === 'true'
		|| process.env.ENABLE_BINANCE_ORDER_AUDIT === 'true'
		|| process.env.ENABLE_FIRESTORE_NEWS_ANALYSIS === 'true';
}

function getAlertStorageRetentionDays() {
	const rawValue = process.env.ALERT_STORAGE_RETENTION_DAYS;
	if (rawValue === undefined) {
		return DEFAULT_ALERT_STORAGE_RETENTION_DAYS;
	}

	const normalizedValue = rawValue.trim();
	const parsedValue = Number(normalizedValue);
	if (!/^\d+$/.test(normalizedValue)
		|| !Number.isSafeInteger(parsedValue)
		|| parsedValue < 1
		|| parsedValue > MAX_ALERT_STORAGE_RETENTION_DAYS) {
		if (lastRetentionWarningValue !== rawValue) {
			console.warn('[AlertStorageService] Invalid ALERT_STORAGE_RETENTION_DAYS configuration, using default');
			lastRetentionWarningValue = rawValue;
		}
		return DEFAULT_ALERT_STORAGE_RETENTION_DAYS;
	}

	lastRetentionWarningValue = null;
	return parsedValue;
}

function clampLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_PAGE_SIZE;
	}

	return Math.min(limit, MAX_PAGE_SIZE);
}

function getDocTimestamp(document) {
	if (!document || !document.receivedAt || typeof document.receivedAt.toDate !== 'function') {
		return null;
	}

	return document.receivedAt.toDate().toISOString();
}

function getTimestampMillis(value) {
	if (value && typeof value.toMillis === 'function') {
		const millis = value.toMillis();
		return Number.isFinite(millis) ? millis : null;
	}

	if (value && typeof value.toDate === 'function') {
		const millis = value.toDate().getTime();
		return Number.isFinite(millis) ? millis : null;
	}

	if (value instanceof Date) {
		const millis = value.getTime();
		return Number.isFinite(millis) ? millis : null;
	}

	return null;
}

function buildRetentionExpiryTimestamp() {
	return admin.firestore.Timestamp.fromDate(
		new Date(Date.now() + (getAlertStorageRetentionDays() * DAY_MS)),
	);
}

function isRetentionExpired(data) {
	const explicitExpiry = getTimestampMillis(data && data.expiresAt);
	if (explicitExpiry !== null) {
		return explicitExpiry <= Date.now();
	}

	// Legacy documents are aged from their existing event timestamp until a TTL backfill is run.
	const eventTimestamp = getTimestampMillis(data && (data.receivedAt || data.replayedAt));
	return eventTimestamp !== null
		&& eventTimestamp + (getAlertStorageRetentionDays() * DAY_MS) <= Date.now();
}

function formatAlertDocument(doc, options = {}) {
	const data = doc.data() || {};
	const extracted = extractSymbolAndExchange(data);
	const includeEnrichmentSummary = Boolean(
		options.includeEnrichmentSummary ||
		(Array.isArray(options.include) && options.include.includes('enrichment_summary')) ||
		options.include === 'enrichment_summary',
	);
	const docObj = {
		id: doc.id,
		receivedAt: getDocTimestamp(data),
		text: typeof data.text === 'string' ? data.text : '',
		enriched: Boolean(data.enriched),
		enrichmentData: includeEnrichmentSummary
			? formatEnrichmentSummary(data.enrichmentData, data)
			: (data.enrichmentData || null),
		tokenUsage: data.tokenUsage || null,
		channels: Array.isArray(data.channels) ? data.channels : [],
		deliveryResults: Array.isArray(data.deliveryResults) ? data.deliveryResults : [],
		source: typeof data.source === 'string' ? data.source : null,
		useTradingViewData: Boolean(data.useTradingViewData),
		tradingViewEnrichmentApplied: Boolean(data.tradingViewEnrichmentApplied),
	};
	if (includeEnrichmentSummary) {
		docObj.enrichmentSummary = docObj.enrichmentData;
	}
	if (typeof data.requestId === 'string' && data.requestId.trim()) {
		docObj.requestId = data.requestId.trim();
	}
	if (extracted.symbol !== 'unknown') {
		docObj.symbol = extracted.symbol;
	}
	if (extracted.exchange) {
		docObj.exchange = extracted.exchange;
	}
	if (VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(data.tradingViewEnrichmentStatus)) {
		docObj.tradingViewEnrichmentStatus = data.tradingViewEnrichmentStatus;
	}
	if (data.suppressedRepeat === true) {
		docObj.suppressedRepeat = true;
	}
	if (typeof data.eventCategory === 'string') {
		docObj.eventCategory = data.eventCategory;
	}
	if (typeof data.confidence === 'number' && Number.isFinite(data.confidence)) {
		docObj.confidence = data.confidence;
	}
	if (typeof data.sentimentScore === 'number' && Number.isFinite(data.sentimentScore)) {
		docObj.sentimentScore = data.sentimentScore;
	}
	if (typeof data.telegramChatId === 'string' && data.telegramChatId.trim()) {
		docObj.telegramChatId = data.telegramChatId.trim();
	}
	if (typeof data.telegramThreadId === 'number' && Number.isSafeInteger(data.telegramThreadId) && data.telegramThreadId >= 0) {
		docObj.telegramThreadId = data.telegramThreadId;
	}
	if (typeof data.whatsappChatId === 'string' && data.whatsappChatId.trim()) {
		docObj.whatsappChatId = data.whatsappChatId.trim();
	}
	if (typeof data.discordWebhookUrl === 'string' && data.discordWebhookUrl.trim()) {
		docObj.discordWebhookUrl = data.discordWebhookUrl.trim();
	}
	if (typeof data.dedupStatus === 'string') {
		docObj.dedupStatus = data.dedupStatus;
	}
	if (data.truncated === true) {
		docObj.truncated = true;
		if (typeof data.originalLength === 'number' && Number.isFinite(data.originalLength)) {
			docObj.originalLength = data.originalLength;
		}
	}
	return docObj;
}

function getNumericValue(value) {
	const numeric = Number(value);
	return Number.isFinite(numeric) ? numeric : 0;
}

function normalizePromptProvenance(provenance) {
	if (!provenance || typeof provenance !== 'object') {
		return null;
	}

	const name = typeof provenance.name === 'string' && provenance.name.trim()
		? provenance.name.trim()
		: null;
	const source = ['langfuse', 'local'].includes(provenance.source)
		? provenance.source
		: null;

	if (!name || !source) {
		return null;
	}

	return {
		name,
		source,
		label: typeof provenance.label === 'string' && provenance.label.trim()
			? provenance.label.trim()
			: null,
		version: Number.isInteger(provenance.version) ? provenance.version : null,
		schemaDriftDetected: Boolean(provenance.schemaDriftDetected),
	};
}

function sanitizeEnrichmentData(enrichmentData) {
	if (!enrichmentData || typeof enrichmentData !== 'object' || Array.isArray(enrichmentData)) {
		return null;
	}

	const sanitized = { ...enrichmentData };
	if (Object.prototype.hasOwnProperty.call(sanitized, 'promptProvenance')) {
		const promptProvenance = normalizePromptProvenance(sanitized.promptProvenance);
		if (promptProvenance) {
			sanitized.promptProvenance = promptProvenance;
		} else {
			delete sanitized.promptProvenance;
		}
	}

	return sanitized;
}

// Firestore Admin SDK rejects `undefined` field values anywhere in a write.
// Only plain objects are rebuilt; class instances (Date, Firestore Timestamp,
// GeoPoint, DocumentReference, FieldValue) pass through untouched.
function stripUndefinedFieldsDeep(value) {
	if (value === null || typeof value !== 'object') {
		return value;
	}
	if (Array.isArray(value)) {
		return value
			.filter((item) => item !== undefined)
			.map((item) => stripUndefinedFieldsDeep(item));
	}

	const proto = Object.getPrototypeOf(value);
	if (proto !== Object.prototype && proto !== null) {
		return value;
	}

	const result = {};
	for (const [key, item] of Object.entries(value)) {
		if (item !== undefined) {
			result[key] = stripUndefinedFieldsDeep(item);
		}
	}
	return result;
}

function createRiskMetadataCoverageBucket() {
	return {
		denominator: 0,
		fields: Object.fromEntries(
			RISK_METADATA_FIELDS.map(field => [field, { populated: 0, percentage: 0 }]),
		),
	};
}

function createTradingViewStatusCounts() {
	return {
		full: 0,
		partial: 0,
		failed: 0,
		not_applicable: 0,
		unrecorded: 0,
	};
}

function isRiskMetadataPopulated(field, value) {
	if (field === 'setup_type') {
		return typeof value === 'string' && VALID_SETUP_TYPES.has(value.trim().toLowerCase());
	}

	return (typeof value === 'number' && Number.isFinite(value))
		|| (typeof value === 'string' && value.trim().length > 0);
}

function recordRiskMetadataCoverage(bucket, enrichmentData) {
	const data = enrichmentData && typeof enrichmentData === 'object' ? enrichmentData : {};
	bucket.denominator += 1;

	for (const field of RISK_METADATA_FIELDS) {
		if (isRiskMetadataPopulated(field, data[field])) {
			bucket.fields[field].populated += 1;
		}
	}
}

function finalizeRiskMetadataCoverage(bucket) {
	for (const field of RISK_METADATA_FIELDS) {
		const metric = bucket.fields[field];
		metric.percentage = bucket.denominator === 0
			? 0
			: Number(((metric.populated / bucket.denominator) * 100).toFixed(2));
	}
}

function getPromptProvenanceGroup(coverage, provenance) {
	const safeProvenanceKey = provenance
		? {
			name: provenance.name,
			source: provenance.source,
			label: provenance.label,
			version: provenance.version,
		}
		: null;
	const key = JSON.stringify(safeProvenanceKey);
	let group = coverage.byPromptProvenance.find(item => {
		const itemKey = item.provenance
			? JSON.stringify({
				name: item.provenance.name,
				source: item.provenance.source,
				label: item.provenance.label,
				version: item.provenance.version,
			})
			: JSON.stringify(null);
		return itemKey === key;
	});

	if (!group) {
		group = {
			provenance: provenance
				? {
					...safeProvenanceKey,
					schemaDriftDetected: Boolean(provenance.schemaDriftDetected),
				}
				: null,
			...createRiskMetadataCoverageBucket(),
		};
		coverage.byPromptProvenance.push(group);
	} else if (provenance?.schemaDriftDetected && group.provenance) {
		group.provenance.schemaDriftDetected = true;
	}

	return group;
}

function recordRiskMetadataCoverageByProvenance(coverage, enrichmentData) {
	recordRiskMetadataCoverage(coverage, enrichmentData);
	const provenance = normalizePromptProvenance(enrichmentData && enrichmentData.promptProvenance);
	const group = getPromptProvenanceGroup(coverage, provenance);
	recordRiskMetadataCoverage(group, enrichmentData);
}

function finalizeRiskMetadataCoverageByProvenance(coverage) {
	finalizeRiskMetadataCoverage(coverage);
	coverage.byPromptProvenance.forEach(finalizeRiskMetadataCoverage);
}

// ---------------------------------------------------------------------------
// Evidence coverage — tracks how many enriched alerts cited grounding sources.
// Mirrors the riskMetadataCoverage pattern: a top-level bucket plus a
// byPromptProvenance sub-array so regressions can be attributed to a specific
// prompt version vs. the local fallback.
// ---------------------------------------------------------------------------

function createEvidenceCoverageBucket() {
	return {
		denominator: 0,
		zeroSources: { populated: 0, percentage: 0 },
		oneToTwoSources: { populated: 0, percentage: 0 },
		threePlusSources: { populated: 0, percentage: 0 },
		totalSourceCount: 0,
		averageSourceCount: 0,
	};
}

function getSourceCount(enrichmentData) {
	const sources = enrichmentData && typeof enrichmentData === 'object'
		? enrichmentData.sources
		: undefined;
	if (Array.isArray(sources)) {
		return sources.length;
	}
	if (typeof sources === 'number' && Number.isFinite(sources) && sources >= 0) {
		return Math.floor(sources);
	}
	// Legacy records lacking a sources field count as zero (fail-safe: no crash).
	return 0;
}

function extractSourceDomains(sources) {
	if (!Array.isArray(sources)) {
		return [];
	}

	const domains = new Set();
	for (const source of sources) {
		let rawUrl = null;
		if (typeof source === 'string') {
			rawUrl = source;
		} else if (source && typeof source === 'object' && typeof source.url === 'string') {
			rawUrl = source.url;
		}

		if (rawUrl) {
			try {
				const { hostname } = new URL(rawUrl);
				if (hostname) {
					domains.add(hostname.toLowerCase().substring(0, 100));
				}
			} catch {
				// Non-URL strings or invalid URLs are safely ignored
			}
		}
	}

	return Array.from(domains).slice(0, 10);
}

function formatEnrichmentSummary(enrichmentData, docData = {}) {
	if (!enrichmentData || typeof enrichmentData !== 'object' || Array.isArray(enrichmentData)) {
		return null;
	}

	const sentiment = typeof enrichmentData.sentiment === 'string' && enrichmentData.sentiment.trim()
		? enrichmentData.sentiment.trim().substring(0, 32)
		: null;

	const sentimentScore = typeof enrichmentData.sentiment_score === 'number' && Number.isFinite(enrichmentData.sentiment_score)
		? enrichmentData.sentiment_score
		: (typeof enrichmentData.sentimentScore === 'number' && Number.isFinite(enrichmentData.sentimentScore)
			? enrichmentData.sentimentScore
			: null);

	const setupType = typeof enrichmentData.setup_type === 'string' && enrichmentData.setup_type.trim()
		? enrichmentData.setup_type.trim().substring(0, 64)
		: (typeof enrichmentData.setupType === 'string' && enrichmentData.setupType.trim()
			? enrichmentData.setupType.trim().substring(0, 64)
			: null);

	let invalidationLevel = null;
	const rawInvalidation = enrichmentData.invalidation_level !== undefined ? enrichmentData.invalidation_level : enrichmentData.invalidationLevel;
	if (typeof rawInvalidation === 'number' && Number.isFinite(rawInvalidation)) {
		invalidationLevel = rawInvalidation;
	} else if (typeof rawInvalidation === 'string' && rawInvalidation.trim()) {
		invalidationLevel = rawInvalidation.trim().substring(0, 32);
	}

	let targetLevel = null;
	const rawTarget = enrichmentData.target_level !== undefined ? enrichmentData.target_level : enrichmentData.targetLevel;
	if (typeof rawTarget === 'number' && Number.isFinite(rawTarget)) {
		targetLevel = rawTarget;
	} else if (typeof rawTarget === 'string' && rawTarget.trim()) {
		targetLevel = rawTarget.trim().substring(0, 32);
	}

	let riskRewardRatio = null;
	const rawRrr = enrichmentData.risk_reward_ratio !== undefined ? enrichmentData.risk_reward_ratio : enrichmentData.riskRewardRatio;
	if (typeof rawRrr === 'number' && Number.isFinite(rawRrr)) {
		riskRewardRatio = rawRrr;
	} else if (typeof rawRrr === 'string' && rawRrr.trim() && Number.isFinite(Number(rawRrr))) {
		riskRewardRatio = Number(rawRrr);
	}

	const sourceCount = getSourceCount(enrichmentData);
	const sourceDomains = extractSourceDomains(enrichmentData.sources);

	const tradingViewEnrichmentApplied = enrichmentData.tradingViewEnrichmentApplied !== undefined
		? Boolean(enrichmentData.tradingViewEnrichmentApplied)
		: Boolean(docData.tradingViewEnrichmentApplied);

	const tradingViewEnrichmentStatus = VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(enrichmentData.tradingViewEnrichmentStatus)
		? enrichmentData.tradingViewEnrichmentStatus
		: (VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(docData.tradingViewEnrichmentStatus)
			? docData.tradingViewEnrichmentStatus
			: null);

	const promptProvenance = normalizePromptProvenance(enrichmentData.promptProvenance);

	return {
		sentiment,
		sentiment_score: sentimentScore,
		setup_type: setupType,
		invalidation_level: invalidationLevel,
		target_level: targetLevel,
		risk_reward_ratio: riskRewardRatio,
		sourceCount,
		sourceDomains,
		tradingViewEnrichmentApplied,
		tradingViewEnrichmentStatus,
		promptProvenance,
	};
}

function recordEvidenceCoverage(bucket, enrichmentData) {
	bucket.denominator += 1;
	const count = getSourceCount(enrichmentData);
	bucket.totalSourceCount += count;
	if (count === 0) {
		bucket.zeroSources.populated += 1;
	} else if (count <= 2) {
		bucket.oneToTwoSources.populated += 1;
	} else {
		bucket.threePlusSources.populated += 1;
	}
}

function finalizeEvidenceCoverage(bucket) {
	const denom = bucket.denominator;
	const pct = (n) => (denom === 0 ? 0 : Number(((n / denom) * 100).toFixed(2)));
	bucket.zeroSources.percentage = pct(bucket.zeroSources.populated);
	bucket.oneToTwoSources.percentage = pct(bucket.oneToTwoSources.populated);
	bucket.threePlusSources.percentage = pct(bucket.threePlusSources.populated);
	bucket.averageSourceCount = denom === 0
		? 0
		: Number((bucket.totalSourceCount / denom).toFixed(2));
}

function getEvidenceProvenanceGroup(coverage, provenance) {
	const safeProvenanceKey = provenance
		? {
			name: provenance.name,
			source: provenance.source,
			label: provenance.label,
			version: provenance.version,
		}
		: null;
	const key = JSON.stringify(safeProvenanceKey);
	let group = coverage.byPromptProvenance.find(item => {
		const itemKey = item.provenance
			? JSON.stringify({
				name: item.provenance.name,
				source: item.provenance.source,
				label: item.provenance.label,
				version: item.provenance.version,
			})
			: JSON.stringify(null);
		return itemKey === key;
	});

	if (!group) {
		group = {
			provenance: provenance
				? {
					...safeProvenanceKey,
					schemaDriftDetected: Boolean(provenance.schemaDriftDetected),
				}
				: null,
			...createEvidenceCoverageBucket(),
		};
		coverage.byPromptProvenance.push(group);
	} else if (provenance?.schemaDriftDetected && group.provenance) {
		group.provenance.schemaDriftDetected = true;
	}

	return group;
}

function recordEvidenceCoverageByProvenance(coverage, enrichmentData) {
	recordEvidenceCoverage(coverage, enrichmentData);
	const provenance = normalizePromptProvenance(enrichmentData && enrichmentData.promptProvenance);
	const group = getEvidenceProvenanceGroup(coverage, provenance);
	recordEvidenceCoverage(group, enrichmentData);
}

function finalizeEvidenceCoverageByProvenance(coverage) {
	finalizeEvidenceCoverage(coverage);
	coverage.byPromptProvenance.forEach(finalizeEvidenceCoverage);
}

function incrementCounter(target, key) {
	const normalizedKey = typeof key === 'string' && key.trim()
		? key.trim()
		: 'unknown';
	target[normalizedKey] = (target[normalizedKey] || 0) + 1;
}

function parseSymbolFromText(text) {
	if (!text || typeof text !== 'string') {
		return null;
	}

	const cleaned = text.trim();
	if (!cleaned) {
		return null;
	}

	const exchangeMatch = cleaned.match(/(?:^|\b)(?<exchange>[A-Z0-9_]{2,10}):(?<symbol>[A-Z0-9._-]{2,20})(?:\s*\(\s*(?<timeframe>[A-Za-z0-9]+)\s*\))?/i);
	if (exchangeMatch && exchangeMatch.groups && exchangeMatch.groups.symbol) {
		const symbol = exchangeMatch.groups.symbol.toUpperCase();
		const exchange = exchangeMatch.groups.exchange ? exchangeMatch.groups.exchange.toUpperCase() : null;
		return { symbol, exchange };
	}

	const timeframeMatch = cleaned.match(/(?:^|\s)(?<symbol>[A-Z0-9._-]{2,20})\s*\(\s*(?<timeframe>[A-Za-z0-9]+)\s*\)/i);
	if (timeframeMatch && timeframeMatch.groups && timeframeMatch.groups.symbol) {
		const symbol = timeframeMatch.groups.symbol.toUpperCase();
		return { symbol, exchange: null };
	}

	return null;
}

function extractSymbolAndExchange(data) {
	if (!data || typeof data !== 'object') {
		return { symbol: 'unknown', exchange: null };
	}

	if (typeof data.symbol === 'string' && data.symbol.trim()) {
		const sym = data.symbol.trim().toUpperCase();
		if (sym.includes(':')) {
			const parts = sym.split(':');
			return { symbol: parts[1], exchange: parts[0] };
		}
		return {
			symbol: sym,
			exchange: typeof data.exchange === 'string' && data.exchange.trim() ? data.exchange.trim().toUpperCase() : null,
		};
	}

	if (typeof data.ticker === 'string' && data.ticker.trim()) {
		const ticker = data.ticker.trim().toUpperCase();
		if (ticker.includes(':')) {
			const parts = ticker.split(':');
			return { symbol: parts[1], exchange: parts[0] };
		}
		return {
			symbol: ticker,
			exchange: typeof data.exchange === 'string' && data.exchange.trim() ? data.exchange.trim().toUpperCase() : null,
		};
	}

	if (data.enrichmentData && typeof data.enrichmentData === 'object') {
		const candidates = [
			data.enrichmentData.symbol,
			data.enrichmentData.ticker,
			data.enrichmentData.asset,
			data.enrichmentData.original_symbol,
		];
		const found = candidates.find((c) => typeof c === 'string' && c.trim());
		if (found) {
			const sym = found.trim().toUpperCase();
			if (sym.includes(':')) {
				const parts = sym.split(':');
				return { symbol: parts[1], exchange: parts[0] };
			}
			const exchange = typeof data.enrichmentData.exchange === 'string' && data.enrichmentData.exchange.trim()
				? data.enrichmentData.exchange.trim().toUpperCase()
				: (typeof data.exchange === 'string' && data.exchange.trim() ? data.exchange.trim().toUpperCase() : null);
			return { symbol: sym, exchange };
		}
	}

	if (typeof data.text === 'string' && data.text.trim()) {
		const parsed = parseSymbolFromText(data.text);
		if (parsed) {
			return parsed;
		}
	}

	return { symbol: 'unknown', exchange: null };
}

function extractAlertSymbol(data) {
	const result = extractSymbolAndExchange(data);
	return result.symbol;
}

function addTokenUsage(totals, tokenUsage) {
	if (!tokenUsage || typeof tokenUsage !== 'object') {
		return;
	}

	totals.inputTokens += getNumericValue(tokenUsage.inputTokens || tokenUsage.promptTokens);
	totals.outputTokens += getNumericValue(tokenUsage.outputTokens || tokenUsage.completionTokens);
	totals.totalTokens += getNumericValue(tokenUsage.totalTokens || tokenUsage.total);
	totals.totalCost += getNumericValue(tokenUsage.totalCost);
}

function addDeliverySummary(summary, deliveryResults) {
	if (!Array.isArray(deliveryResults)) {
		return;
	}

	for (const result of deliveryResults) {
		if (!result || typeof result !== 'object') {
			continue;
		}

		const channel = typeof result.channel === 'string' && result.channel.trim()
			? result.channel.trim()
			: 'unknown';
		if (!summary.byChannel[channel]) {
			summary.byChannel[channel] = { total: 0, success: 0, failure: 0 };
		}

		summary.byChannel[channel].total += 1;
		if (result.success) {
			summary.byChannel[channel].success += 1;
			summary.totalSuccess += 1;
		} else {
			summary.byChannel[channel].failure += 1;
			summary.totalFailure += 1;
		}
	}
}

function summarizeDeliveryResults(deliveryResults) {
	if (!Array.isArray(deliveryResults)) {
		return [];
	}

	return deliveryResults.map((result) => ({
		channel: typeof result.channel === 'string' ? result.channel : null,
		success: Boolean(result.success),
		messageId: typeof result.messageId === 'string' ? result.messageId : null,
		errorCode: typeof result.errorCode === 'string' ? result.errorCode : null,
		statusCode: Number.isInteger(result.statusCode) ? result.statusCode : null,
	})).filter(result => result.channel);
}

function summarizeTokenUsage(tokenUsage) {
	if (!tokenUsage || typeof tokenUsage !== 'object') {
		return null;
	}

	return {
		inputTokens: getNumericValue(tokenUsage.inputTokens || tokenUsage.promptTokens),
		outputTokens: getNumericValue(tokenUsage.outputTokens || tokenUsage.completionTokens),
		totalTokens: getNumericValue(tokenUsage.totalTokens || tokenUsage.total),
		totalCost: getNumericValue(tokenUsage.totalCost),
	};
}

function truncateAlertText(text) {
	if (typeof text !== 'string') {
		return '';
	}

	return text.length > MAX_EXPORT_TEXT_LENGTH
		? text.substring(0, MAX_EXPORT_TEXT_LENGTH)
		: text;
}

function formatExportRecord(doc, { includeText }) {
	const data = doc.data() || {};
	const record = {
		id: doc.id,
		receivedAt: getDocTimestamp(data),
		source: typeof data.source === 'string' ? data.source : null,
		enriched: Boolean(data.enriched),
		useTradingViewData: Boolean(data.useTradingViewData),
		tradingViewEnrichmentApplied: Boolean(data.tradingViewEnrichmentApplied),
		deliveryResults: summarizeDeliveryResults(data.deliveryResults),
		tokenUsage: summarizeTokenUsage(data.tokenUsage),
	};
	if (typeof data.requestId === 'string' && data.requestId.trim()) {
		record.requestId = data.requestId.trim();
	}
	if (VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(data.tradingViewEnrichmentStatus)) {
		record.tradingViewEnrichmentStatus = data.tradingViewEnrichmentStatus;
	}
	if (typeof data.eventCategory === 'string') {
		record.eventCategory = data.eventCategory;
	}
	if (typeof data.confidence === 'number' && Number.isFinite(data.confidence)) {
		record.confidence = data.confidence;
	}
	if (typeof data.sentimentScore === 'number' && Number.isFinite(data.sentimentScore)) {
		record.sentimentScore = data.sentimentScore;
	}
	if (typeof data.dedupStatus === 'string') {
		record.dedupStatus = data.dedupStatus;
	}

	if (includeText) {
		record.text = truncateAlertText(data.text);
		if (data.truncated === true) {
			record.truncated = true;
			if (typeof data.originalLength === 'number' && Number.isFinite(data.originalLength)) {
				record.originalLength = data.originalLength;
			}
		}
	}

	return record;
}

function collectLatency(samples, value) {
	const numeric = Number(value);
	if (Number.isFinite(numeric) && numeric >= 0) {
		samples.push(numeric);
	}
}

function normalizeProcessingTimeMs(value) {
	if (!Number.isSafeInteger(value) || value < 0 || value > MAX_PROCESSING_TIME_MS) {
		return null;
	}

	return value;
}

function averageLatency(samples) {
	if (samples.length === 0) {
		return null;
	}

	return Math.round(samples.reduce((sum, value) => sum + value, 0) / samples.length);
}

function buildSummaryWindow({ from, to, limit }) {
	const now = new Date();
	const parsedTo = to ? new Date(to) : now;
	const maxWindowMs = MAX_SUMMARY_WINDOW_DAYS * 24 * 60 * 60 * 1000;
	let parsedFrom = from ? new Date(from) : new Date(parsedTo.getTime() - (24 * 60 * 60 * 1000));

	if (parsedTo.getTime() - parsedFrom.getTime() > maxWindowMs) {
		parsedFrom = new Date(parsedTo.getTime() - maxWindowMs);
	}

	if (parsedFrom.getTime() > parsedTo.getTime()) {
		const error = new Error('Invalid summary window. from must be before or equal to to.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	return {
		from: parsedFrom.toISOString(),
		to: parsedTo.toISOString(),
		limit: clampSummaryLimit(limit),
		maxDays: MAX_SUMMARY_WINDOW_DAYS,
	};
}

function buildExportWindow({ from, to, limit }) {
	if (!from || !to) {
		const error = new Error('Export requests require bounded from and to ISO-8601 timestamps.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	const parsedFrom = new Date(from);
	const parsedTo = new Date(to);
	const maxWindowMs = MAX_EXPORT_WINDOW_DAYS * 24 * 60 * 60 * 1000;

	if (parsedFrom.getTime() > parsedTo.getTime()) {
		const error = new Error('Invalid export window. from must be before or equal to to.');
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	if (parsedTo.getTime() - parsedFrom.getTime() > maxWindowMs) {
		const error = new Error(`Invalid export window. Maximum export window is ${MAX_EXPORT_WINDOW_DAYS} days.`);
		error.code = 'INVALID_REQUEST';
		throw error;
	}

	return {
		from: parsedFrom.toISOString(),
		to: parsedTo.toISOString(),
		limit: clampExportLimit(limit),
		maxDays: MAX_EXPORT_WINDOW_DAYS,
	};
}

function clampSummaryLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_SUMMARY_LIMIT;
	}

	return Math.min(limit, MAX_SUMMARY_LIMIT);
}

function clampExportLimit(limit) {
	if (!Number.isInteger(limit) || limit < 1) {
		return DEFAULT_EXPORT_LIMIT;
	}

	return Math.min(limit, MAX_EXPORT_LIMIT);
}

function matchesFilters(alert, filters) {
	if (filters.source && alert.source !== filters.source) {
		return false;
	}

	if (typeof filters.enriched === 'boolean' && alert.enriched !== filters.enriched) {
		return false;
	}

	return true;
}

function createStorageUnavailableError(cause) {
	const error = new Error('Alert storage is enabled but Firestore is unavailable. Check Firestore credentials and project configuration.');
	error.code = STORAGE_UNAVAILABLE_CODE;
	if (cause) {
		error.cause = cause;
	}
	return error;
}

function createInvalidCursorError() {
	const error = new Error(INVALID_CURSOR_MESSAGE);
	error.code = 'INVALID_REQUEST';
	return error;
}

function buildParsedCursorTimestamp(parsedCursor) {
	if (parsedCursor && parsedCursor.timestamp
		&& typeof admin.firestore.Timestamp.fromSeconds === 'function') {
		return admin.firestore.Timestamp.fromSeconds(
			parsedCursor.timestamp.seconds,
			parsedCursor.timestamp.nanoseconds,
		);
	}
	return admin.firestore.Timestamp.fromDate(new Date(parsedCursor.receivedAt));
}

function getDocCursorValues(doc) {
	if (!doc || typeof doc.data !== 'function') {
		return null;
	}

	const data = doc.data() || {};
	const receivedAt = getDocTimestamp(data);
	if (!receivedAt || typeof doc.id !== 'string' || !doc.id) {
		return null;
	}

	return {
		receivedAt,
		documentId: doc.id,
	};
}

function getRawDocCursorValues(doc) {
	if (!doc || typeof doc.data !== 'function') {
		return null;
	}

	const data = doc.data() || {};
	if (!data.receivedAt || typeof data.receivedAt.toDate !== 'function'
		|| typeof doc.id !== 'string' || !doc.id) {
		return null;
	}

	return {
		receivedAt: data.receivedAt,
		documentId: doc.id,
	};
}

/**
 * Initialize Firebase Admin (idempotent) and return Firestore client.
 * Returns null when the feature is disabled or initialization fails.
 *
 * Credential resolution order (matches firebase-admin defaults):
 *   1. GOOGLE_APPLICATION_CREDENTIALS env var (path to service-account JSON file)
 *   2. FIREBASE_SERVICE_ACCOUNT_JSON env var   (inline JSON string, preferred for Render secrets)
 *   3. Application Default Credentials          (GCP / Cloud Run managed identity)
 *
 * @returns {FirebaseFirestore.Firestore | null}
 */
function getFirestore() {
	if (!canInitializeFirestore()) {
		return null;
	}

	if (db) {
		return db;
	}

	try {
		let credential;

		// Option B: inline JSON (preferred for Render.com secret env vars)
		if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
			const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
			credential = admin.credential.cert(serviceAccount);
		}
		// Option A: GOOGLE_APPLICATION_CREDENTIALS file path handled automatically by initializeApp()

		const appOptions = {};
		if (credential) {
			appOptions.credential = credential;
		}
		if (process.env.FIREBASE_PROJECT_ID) {
			appOptions.projectId = process.env.FIREBASE_PROJECT_ID;
		}

		if (!admin.apps.length) {
			admin.initializeApp(appOptions);
		}

		db = admin.firestore();
		console.debug('[AlertStorageService] Firestore client initialized');
	} catch (error) {
		console.warn('[AlertStorageService] Failed to initialize Firestore client:', error.message);
		db = null;
	}

	return db;
}

/**
 * Persist a webhook alert document to the `alerts` Firestore collection.
 *
 * This is designed to be called fire-and-forget from the alert handler.
 * All errors are caught internally — this method never throws.
 *
 * @param {Object} params
 * @param {string}  params.text              - Original alert text
 * @param {boolean} params.enriched          - Whether enrichment ran
 * @param {Object|null} params.enrichmentData - alert.enriched object or null
 * @param {Object|null} params.tokenUsage    - tokenUsage.toJSON() result or null
 * @param {Array<string>} params.channels    - Requested channels used for delivery
 * @param {Array}   params.deliveryResults   - Array of SendResult from notificationManager.sendToAll()
 * @param {boolean} params.useTradingViewData - Whether ?useTradingViewData=true was set on the request
 * @param {number}  params.processingTimeMs  - Bounded handler processing duration in milliseconds
 * @returns {Promise<string|null>} The new Firestore document ID, or null on failure/disabled
 */
async function saveAlertInternal({
	text,
	symbol,
	exchange,
	enriched,
	enrichmentData,
	tokenUsage,
	channels,
	deliveryResults,
	useTradingViewData,
	tradingViewEnrichmentApplied,
	tradingViewEnrichmentStatus,
	suppressedRepeat,
	processingTimeMs,
	source,
	eventCategory,
	confidence,
	sentimentScore,
	dedupStatus,
	requestId,
	telegramChatId,
	telegramThreadId,
	whatsappChatId,
	discordWebhookUrl,
	routing,
}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		return null;
	}

	try {
		const extracted = extractSymbolAndExchange({ text, symbol, exchange, enrichmentData });
		const rawText = typeof text === 'string' ? text : '';
		const truncated = rawText.length > MAX_ALERT_TEXT_LENGTH;
		const effectiveTelegramChatId = telegramChatId || (routing && routing.telegramChatId);
		const effectiveTelegramThreadId = telegramThreadId !== undefined
			? telegramThreadId
			: (routing && routing.telegramThreadId !== undefined ? routing.telegramThreadId : undefined);
		const effectiveWhatsappChatId = whatsappChatId || (routing && routing.whatsappChatId);
		const effectiveDiscordWebhookUrl = discordWebhookUrl || (routing && routing.discordWebhookUrl);

		const document = {
			receivedAt: admin.firestore.FieldValue.serverTimestamp(),
			expiresAt: buildRetentionExpiryTimestamp(),
			text: truncated ? rawText.substring(0, MAX_ALERT_TEXT_LENGTH) : rawText,
			enriched: Boolean(enriched),
			enrichmentData: stripUndefinedFieldsDeep(sanitizeEnrichmentData(enrichmentData)),
			tokenUsage: stripUndefinedFieldsDeep(tokenUsage ?? null),
			channels: Array.isArray(channels) ? channels : [],
			deliveryResults: Array.isArray(deliveryResults)
				? stripUndefinedFieldsDeep(deliveryResults)
				: [],
			source: typeof source === 'string' && source.trim() ? source.trim() : 'webhook',
			useTradingViewData: Boolean(useTradingViewData),
			tradingViewEnrichmentApplied: Boolean(tradingViewEnrichmentApplied),
		};
		if (truncated) {
			document.truncated = true;
			document.originalLength = rawText.length;
		}
		if (typeof requestId === 'string' && requestId.trim()) {
			document.requestId = requestId.trim();
		}
		if (VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(tradingViewEnrichmentStatus)) {
			document.tradingViewEnrichmentStatus = tradingViewEnrichmentStatus;
		}
		if (suppressedRepeat === true) {
			document.suppressedRepeat = true;
			document.deliveryResults = [];
		}
		const normalizedProcessingTimeMs = normalizeProcessingTimeMs(processingTimeMs);
		if (normalizedProcessingTimeMs !== null) {
			document.processingTimeMs = normalizedProcessingTimeMs;
		}

		if (extracted.symbol !== 'unknown') {
			document.symbol = extracted.symbol;
		}
		if (extracted.exchange) {
			document.exchange = extracted.exchange;
		}
		if (typeof eventCategory === 'string' && eventCategory.trim()) {
			document.eventCategory = eventCategory.trim();
		}
		if (typeof confidence === 'number' && Number.isFinite(confidence)) {
			document.confidence = confidence;
		}
		if (typeof sentimentScore === 'number' && Number.isFinite(sentimentScore)) {
			document.sentimentScore = sentimentScore;
		}
		if (typeof dedupStatus === 'string' && dedupStatus.trim()) {
			document.dedupStatus = dedupStatus.trim();
		}
		if (typeof effectiveTelegramChatId === 'string' && effectiveTelegramChatId.trim()) {
			document.telegramChatId = effectiveTelegramChatId.trim();
		}
		if (typeof effectiveTelegramThreadId === 'number' && Number.isSafeInteger(effectiveTelegramThreadId) && effectiveTelegramThreadId >= 0) {
			document.telegramThreadId = effectiveTelegramThreadId;
		}
		if (typeof effectiveWhatsappChatId === 'string' && effectiveWhatsappChatId.trim()) {
			document.whatsappChatId = effectiveWhatsappChatId.trim();
		}
		if (typeof effectiveDiscordWebhookUrl === 'string' && effectiveDiscordWebhookUrl.trim()) {
			document.discordWebhookUrl = effectiveDiscordWebhookUrl.trim();
		}

		const docRef = await firestore.collection(COLLECTION_NAME).add(document);
		console.debug(`[AlertStorageService] Alert stored with ID: ${docRef.id}`);
		return docRef.id;
	} catch (error) {
		console.warn('[AlertStorageService] Failed to store alert in Firestore:', error.message);
		return null;
	}
}

function saveAlert(params) {
	return trackBackgroundTask(saveAlertInternal(params));
}

/**
 * Read stored alerts from Firestore with a descending receivedAt cursor.
 *
 * Filtering stays in memory so the endpoint does not require new composite
 * Firestore indexes for source/enriched combinations.
 *
 * @param {Object} params
 * @param {number} params.limit
 * @param {string|undefined} params.before
 * @param {string|undefined} params.source
 * @param {boolean|undefined} params.enriched
 * @param {string[]|string|undefined} params.include
 * @param {boolean|undefined} params.includeEnrichmentSummary
 * @returns {Promise<{alerts: Array, hasMore: boolean, nextBefore: string|null}|null>}
 */
async function listAlerts({
	limit = DEFAULT_PAGE_SIZE,
	before,
	source,
	enriched,
	include,
	includeEnrichmentSummary,
} = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const pageSize = clampLimit(limit);
	const targetCount = pageSize + 1;
	const scanLimit = Math.max(targetCount, MAX_PAGE_SIZE);
	const matches = [];
	const parsedBeforeCursor = before
		? parseAlertPaginationCursor(before)
		: null;
	if (before && !parsedBeforeCursor) {
		throw createInvalidCursorError();
	}

	let pageCursor = parsedBeforeCursor
		? {
			receivedAt: parsedBeforeCursor.receivedAt,
			documentId: parsedBeforeCursor.documentId,
		}
		: null;

	while (matches.length < targetCount) {
		let query = firestore
			.collection(COLLECTION_NAME)
			.orderBy('receivedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc')
			.limit(scanLimit);
		if (pageCursor) {
			const cursorTimestamp = buildParsedCursorTimestamp(pageCursor);
			if (pageCursor.documentId) {
				query = query.startAfter(cursorTimestamp, pageCursor.documentId);
			} else {
				query = query.where('receivedAt', '<', cursorTimestamp);
			}
		}

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to read alerts from Firestore:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || snapshot.empty || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			break;
		}

		for (const doc of snapshot.docs) {
			if (isRetentionExpired(doc.data() || {})) {
				continue;
			}

			const formatted = formatAlertDocument(doc, { include, includeEnrichmentSummary });
			if (matchesFilters(formatted, { source, enriched })) {
				matches.push(formatted);
				if (matches.length >= targetCount) {
					break;
				}
			}
		}

		const lastDocCursor = getDocCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!lastDocCursor) {
			break;
		}

		pageCursor = lastDocCursor;
		if (snapshot.docs.length < scanLimit) {
			break;
		}
	}

	const alerts = matches.slice(0, pageSize);
	return {
		alerts,
		hasMore: matches.length > pageSize,
		nextBefore: alerts.length > 0
			? encodeAlertPaginationCursor(alerts[alerts.length - 1])
			: null,
	};
}

/**
 * Fetch a single stored alert by its Firestore document ID.
 *
 * @param {string} alertId
 * @returns {Promise<Object|null>}
 */
async function getAlertById(alertId) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	let snapshot;
	try {
		snapshot = await firestore.collection(COLLECTION_NAME).doc(alertId).get();
	} catch (error) {
		console.warn('[AlertStorageService] Failed to read alert from Firestore:', error.message);
		throw createStorageUnavailableError(error);
	}
	if (!snapshot || !snapshot.exists) {
		return null;
	}
	if (isRetentionExpired(snapshot.data() || {})) {
		return null;
	}

	return formatAlertDocument(snapshot);
}

/**
 * Persist a replay attempt separately from the immutable original alert.
 *
 * Each call writes a unique audit document so retries with the same idempotency
 * key do not overwrite history. The HTTP `Idempotency-Replay` contract is
 * preserved upstream by the idempotency middleware, which replays the cached
 * response without re-running this storage write; this layer only sees fresh
 * attempts that survived middleware, so uniqueness is required for audit.
 *
 * @param {Object} params
 * @param {string} params.alertId
 * @param {string} params.idempotencyKey
 * @param {Array<string>} params.channels
 * @param {Array} params.deliveryResults
 * @returns {Promise<string|null>}
 */
async function saveReplayAttempt({ alertId, idempotencyKey, channels, deliveryResults }) {
	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const idempotencyKeyHash = crypto.createHash('sha256').update(idempotencyKey).digest('hex');
	const attemptId = `${Date.now()}_${crypto.randomUUID()}`;
	const replayId = `${alertId}_${idempotencyKeyHash}_${attemptId}`;
	const document = {
		alertId,
		idempotencyKeyHash,
		attemptId,
		channels: Array.isArray(channels) ? channels : [],
		deliveryResults: Array.isArray(deliveryResults) ? deliveryResults : [],
		replayedAt: admin.firestore.FieldValue.serverTimestamp(),
		expiresAt: buildRetentionExpiryTimestamp(),
		source: 'alert-replay',
	};

	try {
		await firestore.collection(REPLAY_COLLECTION_NAME).doc(replayId).set(document, { merge: false });
		return replayId;
	} catch (error) {
		console.warn('[AlertStorageService] Failed to store alert replay attempt:', error.message);
		throw createStorageUnavailableError(error);
	}
}

/**
 * Format a replay document into an API-safe response payload. Only safe fields
 * are exposed: the original idempotency key is never persisted or returned, and
 * delivery results are reduced to a compact summary.
 *
 * @param {Object} doc Firestore snapshot document
 * @returns {Object|null}
 */
function formatReplayDocument(doc) {
	if (!doc || typeof doc.data !== 'function') {
		return null;
	}

	const data = doc.data() || {};
	const replayedAt = data.replayedAt && typeof data.replayedAt.toDate === 'function'
		? data.replayedAt.toDate().toISOString()
		: null;
	const compactDelivery = (Array.isArray(data.deliveryResults) ? data.deliveryResults : []).map((entry) => {
		if (!entry || typeof entry !== 'object') {
			return null;
		}
		const compact = { channel: typeof entry.channel === 'string' ? entry.channel : null };
		if (typeof entry.success === 'boolean') {
			compact.success = entry.success;
		}
		if (typeof entry.messageId === 'string' && entry.messageId) {
			compact.messageId = entry.messageId;
		}
		if (typeof entry.errorCode === 'string' && entry.errorCode) {
			compact.errorCode = entry.errorCode;
		}
		if (typeof entry.statusCode === 'number' && Number.isFinite(entry.statusCode)) {
			compact.statusCode = entry.statusCode;
		}
		return compact;
	}).filter(Boolean);

	return {
		id: typeof data.attemptId === 'string' && data.attemptId
			? data.attemptId
			: crypto.createHash('sha256').update(doc.id).digest('hex').slice(0, 24),
		alertId: typeof data.alertId === 'string' ? data.alertId : null,
		idempotencyKeyHashPrefix: typeof data.idempotencyKeyHash === 'string'
			? data.idempotencyKeyHash.slice(0, 12)
			: null,
		channels: Array.isArray(data.channels) ? data.channels : [],
		deliverySummary: compactDelivery,
		replayedAt,
		attemptId: typeof data.attemptId === 'string' ? data.attemptId : null,
	};
}

function getReplayCursorValues(doc) {
	if (!doc || typeof doc.data !== 'function') {
		return null;
	}
	const data = doc.data() || {};
	const replayedAt = data.replayedAt && typeof data.replayedAt.toDate === 'function'
		? data.replayedAt.toDate().toISOString()
		: null;
	if (!replayedAt || typeof doc.id !== 'string' || !doc.id) {
		return null;
	}
	return { replayedAt, timestamp: data.replayedAt, documentId: doc.id };
}

/**
 * Bounded list of replay audit records with retention filtering and optional
 * alertId filter. Mirrors `listAlerts()` pagination and error semantics.
 *
 * @param {Object} params
 * @param {number|undefined} params.limit
 * @param {string|undefined} params.alertId
 * @param {string|undefined} params.before
 * @returns {Promise<{replays: Array, hasMore: boolean, nextBefore: string|null}|null>}
 */
async function listReplayAttempts({ limit = DEFAULT_PAGE_SIZE, alertId, before } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const pageSize = clampLimit(limit);
	const targetCount = pageSize + 1;
	const scanLimit = Math.max(targetCount, MAX_PAGE_SIZE);
	const matches = [];
	const matchCursors = [];
	const parsedBeforeCursor = before
		? parseAlertPaginationCursor(before)
		: null;
	if (before && !parsedBeforeCursor) {
		throw createInvalidCursorError();
	}
	let pageCursor = parsedBeforeCursor
		? {
			receivedAt: parsedBeforeCursor.receivedAt,
			timestamp: parsedBeforeCursor.timestamp,
			documentId: parsedBeforeCursor.documentId,
		}
		: null;

	while (matches.length < targetCount) {
		let query = firestore
			.collection(REPLAY_COLLECTION_NAME)
			.orderBy('replayedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc')
			.limit(scanLimit);

		if (typeof alertId === 'string' && alertId.trim()) {
			query = firestore
				.collection(REPLAY_COLLECTION_NAME)
				.where('alertId', '==', alertId.trim())
				.orderBy('replayedAt', 'desc')
				.orderBy(admin.firestore.FieldPath.documentId(), 'desc')
				.limit(scanLimit);
		}
		if (pageCursor) {
			const pageTimestamp = buildParsedCursorTimestamp(pageCursor);
			if (pageCursor.documentId) {
				query = query.startAfter(pageTimestamp, pageCursor.documentId);
			} else {
				query = query.where('replayedAt', '<', pageTimestamp);
			}
		}

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to list replay attempts:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			break;
		}

		for (const doc of snapshot.docs) {
			if (isRetentionExpired(doc.data() || {})) {
				continue;
			}
			const formatted = formatReplayDocument(doc);
			const docCursor = getReplayCursorValues(doc);
			if (formatted && docCursor) {
				matches.push(formatted);
				matchCursors.push(docCursor);
				if (matches.length >= targetCount) {
					break;
				}
			}
		}

		const lastDocCursor = getReplayCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!lastDocCursor || snapshot.docs.length < scanLimit) {
			break;
		}
		pageCursor = {
			receivedAt: lastDocCursor.replayedAt,
			timestamp: lastDocCursor.timestamp,
			documentId: lastDocCursor.documentId,
		};
	}

	const hasMore = matches.length > pageSize;
	const replays = hasMore ? matches.slice(0, pageSize) : matches;
	const lastCursor = hasMore ? matchCursors[pageSize - 1] : null;
	const nextBefore = hasMore && lastCursor
		? encodeAlertPaginationCursor({
			receivedAt: lastCursor.replayedAt,
			id: lastCursor.documentId,
			timestamp: lastCursor.timestamp,
		})
		: null;

	return { replays, hasMore, nextBefore };
}

/**
 * Most recent replay metadata for a single alert, formatted for inclusion on
 * `GET /api/alerts/:alertId`. Returns `null` if no replay exists.
 *
 * @param {string} alertId
 * @returns {Promise<Object|null>}
 */
async function getLatestReplayForAlert(alertId) {
	if (!isEnabled() || typeof alertId !== 'string' || !alertId.trim()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	let pageCursor = null;
	while (true) {
		let query = firestore
			.collection(REPLAY_COLLECTION_NAME)
			.where('alertId', '==', alertId.trim())
			.orderBy('replayedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc')
			.limit(MAX_PAGE_SIZE);
		if (pageCursor) {
			query = query.startAfter(pageCursor.timestamp, pageCursor.documentId);
		}

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to read latest replay for alert:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			return null;
		}

		const doc = snapshot.docs.find(d => !isRetentionExpired(d.data() || {}));
		if (doc) {
			return formatReplayDocument(doc);
		}

		const lastDocCursor = getReplayCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!lastDocCursor || snapshot.docs.length < MAX_PAGE_SIZE) {
			return null;
		}
		pageCursor = lastDocCursor;
	}
}

/**
 * Export a bounded set of stored alerts using safe, stable fields only.
 *
 * @param {Object} params
 * @param {string} params.from ISO timestamp, required
 * @param {string} params.to ISO timestamp, required
 * @param {number|undefined} params.limit Maximum documents returned, capped at 1000
 * @param {string|undefined} params.source Optional exact source filter
 * @param {boolean|undefined} params.enriched Optional enriched/plain filter
 * @param {boolean|undefined} params.includeText Include truncated alert text when true
 * @returns {Promise<{window: Object, alerts: Array}>}
 */
async function exportAlerts({ from, to, limit, source, enriched, includeText = false } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const window = buildExportWindow({ from, to, limit });
	const hasFilters = typeof source === 'string' || typeof enriched === 'boolean';
	const scanLimit = Math.max(window.limit, MAX_PAGE_SIZE);
	const docs = [];
	let pageCursor = null;
	while (true) {
		let query = firestore
			.collection(COLLECTION_NAME)
			.where('receivedAt', '>=', admin.firestore.Timestamp.fromDate(new Date(window.from)))
			.where('receivedAt', '<=', admin.firestore.Timestamp.fromDate(new Date(window.to)))
			.orderBy('receivedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc');
		if (pageCursor) {
			query = query.startAfter(pageCursor.receivedAt, pageCursor.documentId);
		}
		query = query.limit(scanLimit);

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to export alerts from Firestore:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			break;
		}

		const activeDocs = snapshot.docs.filter(doc => !isRetentionExpired(doc.data() || {}));
		const matchingDocs = hasFilters
			? activeDocs.filter((doc) => {
				const data = doc.data() || {};
				return matchesFilters({
					source: typeof data.source === 'string' ? data.source : null,
					enriched: Boolean(data.enriched),
				}, { source, enriched });
			})
			: activeDocs;
		docs.push(...matchingDocs.slice(0, window.limit - docs.length));

		if (docs.length >= window.limit || snapshot.docs.length < scanLimit) {
			break;
		}

		pageCursor = getRawDocCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!pageCursor) {
			break;
		}
	}

	const alerts = docs.map(doc => formatExportRecord(doc, { includeText }));

	return {
		window,
		alerts,
	};
}

/**
 * Build bounded aggregate metrics for stored alerts.
 *
 * The endpoint intentionally returns counts and totals only. Raw alert text,
 * provider payloads, credentials, and error details stay out of the response.
 *
 * @param {Object} params
 * @param {string|undefined} params.from ISO timestamp, defaults to 24h before to
 * @param {string|undefined} params.to ISO timestamp, defaults to now
 * @param {number|undefined} params.limit Maximum matching documents aggregated, capped at 1000
 * @param {string|undefined} params.source Optional exact source filter
 * @param {boolean|undefined} params.enriched Optional enriched/plain filter
 * @returns {Promise<Object|null>}
 */
async function summarizeAlerts({ from, to, limit, source, enriched } = {}) {
	if (!isEnabled()) {
		return null;
	}

	const firestore = getFirestore();
	if (!firestore) {
		throw createStorageUnavailableError();
	}

	const window = buildSummaryWindow({ from, to, limit });
	const hasFilters = typeof source === 'string' || typeof enriched === 'boolean';
	const scanLimit = Math.max(window.limit, MAX_PAGE_SIZE);
	const docs = [];
	let pageCursor = null;
	while (true) {
		let query = firestore
			.collection(COLLECTION_NAME)
			.where('receivedAt', '>=', admin.firestore.Timestamp.fromDate(new Date(window.from)))
			.where('receivedAt', '<=', admin.firestore.Timestamp.fromDate(new Date(window.to)))
			.orderBy('receivedAt', 'desc')
			.orderBy(admin.firestore.FieldPath.documentId(), 'desc');
		if (pageCursor) {
			query = query.startAfter(pageCursor.receivedAt, pageCursor.documentId);
		}
		query = query.limit(scanLimit);

		let snapshot;
		try {
			snapshot = await query.get();
		} catch (error) {
			console.warn('[AlertStorageService] Failed to summarize alerts from Firestore:', error.message);
			throw createStorageUnavailableError(error);
		}

		if (!snapshot || !Array.isArray(snapshot.docs) || snapshot.docs.length === 0) {
			break;
		}

		const activeDocs = snapshot.docs.filter(doc => !isRetentionExpired(doc.data() || {}));
		const matchingDocs = hasFilters
			? activeDocs.filter((doc) => {
				const data = doc.data() || {};
				return matchesFilters({
					source: typeof data.source === 'string' ? data.source : null,
					enriched: Boolean(data.enriched),
				}, { source, enriched });
			})
			: activeDocs;
		docs.push(...matchingDocs.slice(0, window.limit - docs.length));

		if (docs.length >= window.limit || snapshot.docs.length < scanLimit) {
			break;
		}

		pageCursor = getRawDocCursorValues(snapshot.docs[snapshot.docs.length - 1]);
		if (!pageCursor) {
			break;
		}
	}

	const summary = {
		window,
		totalAlerts: 0,
		bySource: {},
		bySymbol: {},
		byFeatureFlag: {
			enriched: 0,
			plain: 0,
			tradingViewData: 0,
			tradingViewDataApplied: 0,
			withoutTradingViewData: 0,
		},
		enrichment: {
			enrichedAlerts: 0,
			plainAlerts: 0,
			tradingViewStatusCounts: createTradingViewStatusCounts(),
			riskMetadataCoverage: {
				...createRiskMetadataCoverageBucket(),
				byPromptProvenance: [],
			},
			evidenceCoverage: {
				...createEvidenceCoverageBucket(),
				byPromptProvenance: [],
			},
			tokenUsage: {
				inputTokens: 0,
				outputTokens: 0,
				totalTokens: 0,
				totalCost: 0,
			},
		},
		delivery: {
			totalSuccess: 0,
			totalFailure: 0,
			byChannel: {},
		},
		latency: {
			averageProcessingMs: null,
			averageDeliveryMs: null,
		},
	};
	const processingLatencySamples = [];
	const deliveryLatencySamples = [];

	for (const doc of docs) {
		const data = doc.data() || {};
		const alertEnriched = Boolean(data.enriched);
		const useTradingViewData = Boolean(data.useTradingViewData);
		const tradingViewEnrichmentApplied = Boolean(data.tradingViewEnrichmentApplied);
		const tradingViewEnrichmentStatus = data.tradingViewEnrichmentStatus;

		summary.totalAlerts += 1;
		incrementCounter(summary.bySource, data.source);
		incrementCounter(summary.bySymbol, extractAlertSymbol(data));

		if (alertEnriched) {
			summary.byFeatureFlag.enriched += 1;
			summary.enrichment.enrichedAlerts += 1;
			recordRiskMetadataCoverageByProvenance(summary.enrichment.riskMetadataCoverage, data.enrichmentData);
			recordEvidenceCoverageByProvenance(summary.enrichment.evidenceCoverage, data.enrichmentData);
		} else {
			summary.byFeatureFlag.plain += 1;
			summary.enrichment.plainAlerts += 1;
		}

		if (VALID_TRADINGVIEW_ENRICHMENT_STATUSES.has(tradingViewEnrichmentStatus)) {
			summary.enrichment.tradingViewStatusCounts[tradingViewEnrichmentStatus] += 1;
		} else if (useTradingViewData) {
			summary.enrichment.tradingViewStatusCounts.unrecorded += 1;
		} else {
			summary.enrichment.tradingViewStatusCounts.not_applicable += 1;
		}

		if (useTradingViewData) {
			summary.byFeatureFlag.tradingViewData += 1;
			if (tradingViewEnrichmentApplied) {
				summary.byFeatureFlag.tradingViewDataApplied += 1;
			}
		} else {
			summary.byFeatureFlag.withoutTradingViewData += 1;
		}

		addTokenUsage(summary.enrichment.tokenUsage, data.tokenUsage);
		addDeliverySummary(summary.delivery, data.deliveryResults);
		collectLatency(processingLatencySamples, data.processingTimeMs ?? data.processing_time_ms);

		if (Array.isArray(data.deliveryResults)) {
			for (const result of data.deliveryResults) {
				collectLatency(deliveryLatencySamples, result && (result.latencyMs || result.deliveryLatencyMs || result.durationMs));
			}
		}
	}

	finalizeRiskMetadataCoverageByProvenance(summary.enrichment.riskMetadataCoverage);
	finalizeEvidenceCoverageByProvenance(summary.enrichment.evidenceCoverage);
	summary.enrichment.tokenUsage.totalCost = Number(summary.enrichment.tokenUsage.totalCost.toFixed(6));
	summary.latency.averageProcessingMs = averageLatency(processingLatencySamples);
	summary.latency.averageDeliveryMs = averageLatency(deliveryLatencySamples);

	return summary;
}

module.exports = {
	isEnabled,
	saveAlert,
	listAlerts,
	getAlertById,
	summarizeAlerts,
	exportAlerts,
	saveReplayAttempt,
	listReplayAttempts,
	getLatestReplayForAlert,
	parseSymbolFromText,
	extractSymbolAndExchange,
	extractAlertSymbol,
	formatEnrichmentSummary,
	extractSourceDomains,
	formatAlertDocument,
	STORAGE_UNAVAILABLE_CODE,
	INVALID_CURSOR_MESSAGE,
	parseAlertPaginationCursor,
	MAX_ALERT_TEXT_LENGTH,
	// Exported for testing
	getFirestore,
	COLLECTION_NAME,
	REPLAY_COLLECTION_NAME,
	// Reset the cached db singleton between tests without module reloading
	_resetForTesting() {
		db = null;
		lastRetentionWarningValue = null;
	},
};
