'use strict';

/**
 * SignalOutcomeService — optional Firestore-backed shadow-mode signal outcome tracker.
 *
 * Feature-gated: ENABLE_SIGNAL_OUTCOME_TRACKING=true required.
 * Fail-open: any Firestore error is caught and logged; alert delivery is NEVER blocked.
 *
 * Collection: signal-outcomes
 * Document ID: auto-generated by Firestore
 *
 * Signal document schema:
 *   requestId      - string  — idempotency key or generated UUID
 *   source         - string  — 'webhook' | 'news-monitor' | 'scanner' | 'expanded-analysis'
 *   symbol         - string  — normalized symbol (e.g. 'BTCUSDT')
 *   exchange       - string  — exchange prefix (e.g. 'BINANCE')
 *   timeframe      - string  — e.g. '1h', '4h', '1D'
 *   setupType      - string  — e.g. 'breakout', 'reversal', 'momentum'
 *   side           - string  — 'long' | 'short' | 'neutral' | null
 *   score          - number  — confidence score 0–1 if available, else null
 *   entryPrice     - number  — price at decision time, null if unavailable
 *   stopPrice      - number  — stop-loss level, null if unavailable
 *   targetPrice    - number  — take-profit level, null if unavailable
 *   alertText      - string  — first 500 chars of the original alert text
 *   recordedAt     - Timestamp — server-side timestamp of signal capture
 *   outcomes       - object  — evaluation windows: { '1h': null, '4h': null, '1D': null, '1W': null }
 *                              Each window is null (pending) or { price, returnPct, evaluatedAt }
 *   evaluated      - boolean — true once at least one outcome window is filled
 *   shadowMode     - boolean — always true (marks this as a shadow-mode diagnostic record)
 */

const admin = require('firebase-admin');

const COLLECTION_NAME = 'signal-outcomes';
const DEFAULT_SUMMARY_LIMIT = 200;
const MAX_SUMMARY_LIMIT = 500;
const OUTCOME_WINDOWS = ['1h', '4h', '1D', '1W'];

// Lazy Firestore singleton (shared with other storage services via firebase-admin)
let db = null;

/**
 * Whether shadow-mode outcome tracking is enabled.
 * @returns {boolean}
 */
function isEnabled() {
	return process.env.ENABLE_SIGNAL_OUTCOME_TRACKING === 'true';
}

/**
 * Whether the Firestore client is initialized and ready.
 * @returns {boolean}
 */
function isReady() {
	if (!isEnabled()) {
		return false;
	}
	return getFirestore() !== null;
}

/**
 * Initialize Firebase Admin (idempotent) and return Firestore client.
 * Reuses the existing admin app if already initialized by AlertStorageService.
 * Returns null when the feature is disabled or initialization fails.
 *
 * @returns {FirebaseFirestore.Firestore | null}
 */
function getFirestore() {
	if (!isEnabled()) {
		return null;
	}

	if (db) {
		return db;
	}

	try {
		let credential;

		if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
			const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
			credential = admin.credential.cert(serviceAccount);
		}

		const appOptions = {};
		if (credential) {
			appOptions.credential = credential;
		}
		if (process.env.FIREBASE_PROJECT_ID) {
			appOptions.projectId = process.env.FIREBASE_PROJECT_ID;
		}

		if (!admin.apps.length) {
			admin.initializeApp(appOptions);
		}

		db = admin.firestore();
		console.debug('[SignalOutcomeService] Firestore client initialized');
	} catch (error) {
		console.warn('[SignalOutcomeService] Failed to initialize Firestore:', error.message);
		db = null;
	}

	return db;
}

/**
 * Normalize a raw signal payload into the canonical outcome-tracking schema.
 *
 * @param {Object} raw - Raw signal data from any source
 * @returns {Object} Normalized signal record
 */
function normalizeSignal(raw) {
	const {
		requestId,
		source,
		symbol,
		exchange,
		timeframe,
		setupType,
		side,
		score,
		entryPrice,
		stopPrice,
		targetPrice,
		alertText,
	} = raw || {};

	return {
		requestId: typeof requestId === 'string' ? requestId : null,
		source: typeof source === 'string' ? source : 'unknown',
		symbol: typeof symbol === 'string' ? symbol.toUpperCase() : null,
		exchange: typeof exchange === 'string' ? exchange.toUpperCase() : null,
		timeframe: typeof timeframe === 'string' ? timeframe : null,
		setupType: typeof setupType === 'string' ? setupType : null,
		side: ['long', 'short', 'neutral'].includes(side) ? side : null,
		score: typeof score === 'number' && score >= 0 && score <= 1 ? score : null,
		entryPrice: typeof entryPrice === 'number' ? entryPrice : null,
		stopPrice: typeof stopPrice === 'number' ? stopPrice : null,
		targetPrice: typeof targetPrice === 'number' ? targetPrice : null,
		alertText: typeof alertText === 'string' ? alertText.substring(0, 500) : null,
		outcomes: OUTCOME_WINDOWS.reduce((acc, w) => ({ ...acc, [w]: null }), {}),
		evaluated: false,
		shadowMode: true,
	};
}

/**
 * Record a new trading signal for future outcome evaluation.
 * Fail-open: errors are logged and swallowed; alert delivery is never blocked.
 *
 * @param {Object} raw - Raw signal metadata
 * @returns {Promise<string|null>} Firestore document ID or null on failure/disabled
 */
async function recordSignal(raw) {
	const firestore = getFirestore();
	if (!firestore) {
		return null;
	}

	try {
		const signal = normalizeSignal(raw);
		signal.recordedAt = admin.firestore.FieldValue.serverTimestamp();

		const docRef = await firestore.collection(COLLECTION_NAME).add(signal);
		console.debug('[SignalOutcomeService] Signal recorded:', docRef.id, '| source:', signal.source, '| symbol:', signal.symbol);
		return docRef.id;
	} catch (error) {
		console.warn('[SignalOutcomeService] recordSignal error (fail-open):', error.message);
		return null;
	}
}

/**
 * Compute aggregate metrics over a set of signal outcome records.
 *
 * @param {Array<Object>} records - Array of signal documents
 * @returns {Object} Metrics object
 */
function computeMetrics(records) {
	const total = records.length;

	if (total === 0) {
		return {
			total: 0,
			evaluated: 0,
			pending: 0,
			hitRate: null,
			averageReturn: null,
			maxFavorableExcursion: null,
			maxAdverseExcursion: null,
			message: 'No measurements found',
		};
	}

	const evaluated = records.filter(r => r.evaluated === true);
	const windows = {};

	for (const window of OUTCOME_WINDOWS) {
		const windowRecords = evaluated.filter(r => r.outcomes && r.outcomes[window] !== null);
		if (windowRecords.length === 0) {
			windows[window] = { count: 0, hitRate: null, averageReturn: null };
			continue;
		}

		const returns = windowRecords.map(r => r.outcomes[window]?.returnPct ?? null).filter(v => v !== null);
		const hits = returns.filter(v => v > 0);

		windows[window] = {
			count: windowRecords.length,
			hitRate: returns.length > 0 ? (hits.length / returns.length) : null,
			averageReturn: returns.length > 0 ? (returns.reduce((a, b) => a + b, 0) / returns.length) : null,
			maxFavorableExcursion: returns.length > 0 ? Math.max(...returns) : null,
			maxAdverseExcursion: returns.length > 0 ? Math.min(...returns) : null,
		};
	}

	return {
		total,
		evaluated: evaluated.length,
		pending: total - evaluated.length,
		windows,
		bySource: _groupBy(records, 'source'),
		message: null,
	};
}

function _groupBy(records, field) {
	const groups = {};
	for (const record of records) {
		const key = record[field] || 'unknown';
		groups[key] = (groups[key] || 0) + 1;
	}
	return groups;
}

/**
 * Retrieve signal outcome summary metrics.
 *
 * @param {Object} options
 * @param {number} [options.limit] - Max records to analyze
 * @param {string} [options.source] - Filter by source (e.g. 'news-monitor')
 * @param {string} [options.symbol] - Filter by symbol (e.g. 'BTCUSDT')
 * @returns {Promise<Object>} Metrics object
 */
async function getSummary({ limit, source, symbol } = {}) {
	const firestore = getFirestore();
	if (!firestore) {
		return {
			enabled: false,
			message: 'Signal outcome tracking is disabled (ENABLE_SIGNAL_OUTCOME_TRACKING not set)',
		};
	}

	const clampedLimit = Math.min(
		Number.isInteger(limit) && limit > 0 ? limit : DEFAULT_SUMMARY_LIMIT,
		MAX_SUMMARY_LIMIT,
	);

	try {
		let query = firestore.collection(COLLECTION_NAME).orderBy('recordedAt', 'desc').limit(clampedLimit);

		if (typeof source === 'string' && source.trim().length > 0) {
			query = query.where('source', '==', source.trim());
		}
		if (typeof symbol === 'string' && symbol.trim().length > 0) {
			query = query.where('symbol', '==', symbol.trim().toUpperCase());
		}

		const snapshot = await query.get();
		const records = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));

		return {
			enabled: true,
			ready: true,
			count: records.length,
			limit: clampedLimit,
			filters: { source: source || null, symbol: symbol || null },
			metrics: computeMetrics(records),
		};
	} catch (error) {
		console.warn('[SignalOutcomeService] getSummary error:', error.message);
		return {
			enabled: true,
			ready: false,
			error: 'STORAGE_UNAVAILABLE',
			message: error.message,
		};
	}
}

module.exports = {
	isEnabled,
	isReady,
	recordSignal,
	normalizeSignal,
	computeMetrics,
	getSummary,
	COLLECTION_NAME,
	OUTCOME_WINDOWS,
	// Testing hook
	_resetForTesting() {
		db = null;
	},
};
