const { chmodSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } = require('fs');
const { spawnSync } = require('child_process');
const { tmpdir } = require('os');
const { join } = require('path');

const detectScriptPath = join(
	__dirname,
	'../../.agents/skills/agent-cross-review/scripts/detect-agent-prs.sh',
);
const skillPath = join(
	__dirname,
	'../../.agents/skills/agent-cross-review/SKILL.md',
);
const openaiYamlPath = join(
	__dirname,
	'../../.agents/skills/agent-cross-review/agents/openai.yaml',
);
const rubricPath = join(
	__dirname,
	'../../.agents/skills/agent-cross-review/references/cabros-bot-review-rubric.md',
);

describe('agent-cross-review skill structure and documentation', () => {
	it('contains valid frontmatter in SKILL.md', () => {
		expect(existsSync(skillPath)).toBe(true);
		const content = readFileSync(skillPath, 'utf8');

		expect(content).toMatch(/^---\nname:\s*agent-cross-review\ndescription:\s*.+\n---/);
		expect(content).toContain('Agent Cross-Review');
		expect(content).toContain('detect-agent-prs.sh');
		expect(content).toContain('cabros-bot-review-rubric.md');
		expect(content).toContain('APPROVE');
		expect(content).toContain('REQUEST_CHANGES');
	});

	it('contains valid openai.yaml interface configuration', () => {
		expect(existsSync(openaiYamlPath)).toBe(true);
		const content = readFileSync(openaiYamlPath, 'utf8');

		expect(content).toContain('display_name: "Agent Cross-Review"');
		expect(content).toContain('short_description:');
		expect(content).toContain('default_prompt:');
	});

	it('contains comprehensive Cabros Bot review rubric in references', () => {
		expect(existsSync(rubricPath)).toBe(true);
		const content = readFileSync(rubricPath, 'utf8');

		expect(content).toContain('Fail-Open');
		expect(content).toContain('MarkdownV2');
		expect(content).toContain('AbortController');
		expect(content).toContain('Sanitize Undefined Values');
		expect(content).toContain('timingSafeEqual');
		expect(content).toContain('Remote Config');
		expect(content).toContain('openapi.json');
		expect(content).toContain('CabrosBot.postman_collection.json');
	});
});

describe('detect-agent-prs.sh script', () => {
	it('has valid bash syntax', () => {
		const result = spawnSync('bash', ['-n', detectScriptPath], { encoding: 'utf8' });
		expect(result.status).toBe(0);
		expect(result.stderr).toBe('');
	});

	it('supports --help option', () => {
		const result = spawnSync('bash', [detectScriptPath, '--help'], { encoding: 'utf8' });
		expect(result.status).toBe(0);
		expect(result.stdout).toContain('Usage: detect-agent-prs.sh');
		expect(result.stdout).toContain('--agent');
		expect(result.stdout).toContain('--exclude-self');
		expect(result.stdout).toContain('--json');
	});

	it('correctly classifies PRs and distinguishes human branches from copilot', () => {
		const tempDir = mkdtempSync(join(tmpdir(), 'agent-cross-review-test-'));
		const mockGhPath = join(tempDir, 'gh');

		const samplePrs = [
			{
				number: 101,
				title: 'feat: add feature from codex',
				body: 'Closes #100\nGenerated by Codex',
				headRefName: 'codex/issue-100-feature',
				author: { login: 'francovp' },
				createdAt: '2026-08-30T00:00:00Z',
				state: 'OPEN',
				url: 'https://github.com/francovp/cabros-bot/pull/101',
				commits: [{ authors: [{ name: 'Franco Valerio', email: 'franco@example.com' }], messageHeadline: 'feat: add feature', messageBody: '' }],
			},
			{
				number: 102,
				title: 'fix: copilot fix',
				body: 'Co-authored-by: Copilot App',
				headRefName: 'francovp-studious-telegram',
				author: { login: 'francovp' },
				createdAt: '2026-08-30T01:00:00Z',
				state: 'OPEN',
				url: 'https://github.com/francovp/cabros-bot/pull/102',
				commits: [{ authors: [{ name: 'Copilot CLI', email: 'copilot@anthropic.local' }], messageHeadline: 'fix: copilot fix', messageBody: '' }],
			},
			{
				number: 103,
				title: 'chore: antigravity work',
				body: 'Antigravity skill update',
				headRefName: 'agent_cross_review_skill',
				author: { login: 'francovp' },
				createdAt: '2026-08-30T02:00:00Z',
				state: 'OPEN',
				url: 'https://github.com/francovp/cabros-bot/pull/103',
				commits: [{ authors: [{ name: 'Franco Valerio', email: 'franco@example.com' }], messageHeadline: 'chore: antigravity work', messageBody: '' }],
			},
			{
				number: 104,
				title: 'fix: human fix on personal branch',
				body: 'Fixing typo manually',
				headRefName: 'francovp-fix-alert',
				author: { login: 'francovp' },
				createdAt: '2026-08-30T03:00:00Z',
				state: 'OPEN',
				url: 'https://github.com/francovp/cabros-bot/pull/104',
				commits: [{ authors: [{ name: 'Franco Valerio', email: 'franco@example.com' }], messageHeadline: 'fix: typo', messageBody: '' }],
			},
		];

		writeFileSync(
			mockGhPath,
			`#!/bin/sh
if [ "$1" = "repo" ]; then
  echo "francovp/cabros-bot"
elif [ "$1" = "auth" ]; then
  if [ "$2" = "status" ]; then
    echo "Logged in to github.com as francovp"
  fi
elif [ "$1" = "pr" ]; then
  cat << 'EOF'
${JSON.stringify(samplePrs)}
EOF
fi
`,
		);
		chmodSync(mockGhPath, 0o755);

		const env = { ...process.env, PATH: `${tempDir}:${process.env.PATH}` };

		// 1. Fetch all with JSON output
		const resultAll = spawnSync('bash', [detectScriptPath, '--json'], { env, encoding: 'utf8' });
		expect(resultAll.status).toBe(0);
		const parsedAll = JSON.parse(resultAll.stdout);
		expect(parsedAll).toHaveLength(4);
		expect(parsedAll[0].detectedAgent).toBe('codex');
		expect(parsedAll[1].detectedAgent).toBe('github-copilot');
		expect(parsedAll[2].detectedAgent).toBe('antigravity');
		expect(parsedAll[3].detectedAgent).toBe('human');

		// 2. Filter by --agent codex
		const resultCodex = spawnSync('bash', [detectScriptPath, '--agent', 'codex', '--json'], { env, encoding: 'utf8' });
		expect(resultCodex.status).toBe(0);
		const parsedCodex = JSON.parse(resultCodex.stdout);
		expect(parsedCodex).toHaveLength(1);
		expect(parsedCodex[0].number).toBe(101);

		// 3. Exclude self with --exclude-self antigravity
		const resultExclude = spawnSync('bash', [detectScriptPath, '--exclude-self', 'antigravity', '--json'], { env, encoding: 'utf8' });
		expect(resultExclude.status).toBe(0);
		const parsedExclude = JSON.parse(resultExclude.stdout);
		expect(parsedExclude).toHaveLength(3);
		expect(parsedExclude.map(p => p.detectedAgent)).toEqual(['codex', 'github-copilot', 'human']);

		rmSync(tempDir, { recursive: true, force: true });
	});

	it('propagates gh command errors with non-zero exit and error output', () => {
		const tempDir = mkdtempSync(join(tmpdir(), 'agent-cross-review-fail-'));
		const mockGhPath = join(tempDir, 'gh');

		writeFileSync(
			mockGhPath,
			`#!/bin/sh
if [ "$1" = "repo" ]; then
  echo "francovp/cabros-bot"
elif [ "$1" = "auth" ]; then
  echo "Logged in to github.com as francovp"
elif [ "$1" = "pr" ]; then
  echo "HTTP 401: Bad credentials" >&2
  exit 1
fi
`,
		);
		chmodSync(mockGhPath, 0o755);

		const env = { ...process.env, PATH: `${tempDir}:${process.env.PATH}` };

		const result = spawnSync('bash', [detectScriptPath], { env, encoding: 'utf8' });
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('Error: Failed to list PRs');
		expect(result.stderr).toContain('Bad credentials');

		rmSync(tempDir, { recursive: true, force: true });
	});
});
