'use strict';

const fs = require('node:fs');
const path = require('node:path');

jest.mock('node:readline', () => ({
	createInterface: jest.fn(() => ({
		question: jest.fn((_q, cb) => cb('')),
		close: jest.fn(),
	})),
}));

const wizard = require('../../scripts/setup-wizard');

describe('parseArgs', () => {
	it('defaults to interactive without flags', () => {
		const opts = wizard.parseArgs(['node', 'script.js']);
		expect(opts.nonInteractive).toBe(false);
		expect(opts.minimal).toBe(false);
		expect(opts.dryRun).toBe(false);
		expect(opts.help).toBe(false);
	});

	it('parses --non-interactive and --minimal together', () => {
		const opts = wizard.parseArgs(['node', 'script.js', '--non-interactive', '--minimal']);
		expect(opts.nonInteractive).toBe(true);
		expect(opts.minimal).toBe(true);
	});

	it('parses --help and --dry-run', () => {
		const opts = wizard.parseArgs(['node', 'script.js', '--help', '--dry-run']);
		expect(opts.help).toBe(true);
		expect(opts.dryRun).toBe(true);
	});
});

describe('parseExistingEnv', () => {
	it('parses simple key=value pairs', () => {
		const parsed = wizard.parseExistingEnv('FOO=bar\nBAZ=qux\n');
		expect(parsed).toEqual({ FOO: 'bar', BAZ: 'qux' });
	});

	it('strips comments and blank lines', () => {
		const parsed = wizard.parseExistingEnv('# comment\n\nFOO=bar\n# trailing\n');
		expect(parsed).toEqual({ FOO: 'bar' });
	});

	it('unwraps quoted values', () => {
		const parsed = wizard.parseExistingEnv('FOO="hello world"\nBAR=\'single\'\n');
		expect(parsed).toEqual({ FOO: 'hello world', BAR: 'single' });
	});

	it('returns empty object for empty content', () => {
		const parsed = wizard.parseExistingEnv('');
		expect(parsed).toEqual({});
	});
});

describe('serializeEnv', () => {
	it('renders sorted key=value pairs', () => {
		const out = wizard.serializeEnv([['Z', '1'], ['A', '2']]);
		expect(out).toMatch(/^# Generated by/);
		expect(out).toMatch(/A=2/);
		expect(out).toMatch(/Z=1/);
	});

	it('quotes values with whitespace', () => {
		const out = wizard.serializeEnv([['KEY', 'has space']]);
		expect(out).toMatch(/KEY="has space"/);
	});
});

describe('generateApiKey and generateCallbackSecret', () => {
	it('produces a 32-byte base64url-encoded key', () => {
		const key = wizard.generateApiKey();
		expect(typeof key).toBe('string');
		expect(key.length).toBeGreaterThanOrEqual(42);
		expect(key.length).toBeLessThanOrEqual(44);
		expect(key).toMatch(/^[A-Za-z0-9_-]+$/);
	});

	it('produces a unique value per call', () => {
		expect(wizard.generateApiKey()).not.toEqual(wizard.generateApiKey());
	});

	it('generateCallbackSecret returns base64url with no padding', () => {
		const secret = wizard.generateCallbackSecret();
		expect(secret).not.toMatch(/=/);
		expect(secret).toMatch(/^[A-Za-z0-9_-]+$/);
	});
});

describe('diffEnvKeys', () => {
	it('identifies added and changed keys', () => {
		const existing = { A: '1', B: '2' };
		const next = new Map([['A', '1'], ['B', '3'], ['C', '4']]);
		const diff = wizard.diffEnvKeys(existing, next);
		expect(diff.added).toEqual(['C']);
		expect(diff.changed).toEqual(['B']);
	});

	it('accepts plain object next', () => {
		const existing = { A: '1' };
		const next = { A: '1', B: '2' };
		const diff = wizard.diffEnvKeys(existing, next);
		expect(diff.added).toEqual(['B']);
		expect(diff.changed).toEqual([]);
	});

	it('returns empty arrays when entries are identical', () => {
		const existing = { A: '1' };
		const next = new Map([['A', '1']]);
		const diff = wizard.diffEnvKeys(existing, next);
		expect(diff.added).toEqual([]);
		expect(diff.changed).toEqual([]);
	});
});

describe('resolveMinimalAnswers', () => {
	it('generates fresh keys and disables telegram bot', () => {
		const a = wizard.resolveMinimalAnswers();
		expect(a.WEBHOOK_API_KEY).toMatch(/^[A-Za-z0-9_-]+$/);
		expect(a.JOB_CALLBACK_SIGNING_SECRET).toMatch(/^[A-Za-z0-9_-]+$/);
		expect(a.ENABLE_TELEGRAM_BOT).toBe('false');
	});

	it('produces distinct keys across calls', () => {
		const a = wizard.resolveMinimalAnswers();
		const b = wizard.resolveMinimalAnswers();
		expect(a.WEBHOOK_API_KEY).not.toEqual(b.WEBHOOK_API_KEY);
		expect(a.JOB_CALLBACK_SIGNING_SECRET).not.toEqual(b.JOB_CALLBACK_SIGNING_SECRET);
	});
});

describe('REQUIRED_KEYS', () => {
	it('lists WEBHOOK_API_KEY', () => {
		expect(wizard.REQUIRED_KEYS).toContain('WEBHOOK_API_KEY');
	});
});

describe('backupEnv', () => {
	it('returns null when source does not exist', () => {
		expect(wizard.backupEnv('/tmp/cabros-wizard-nonexistent-' + Date.now())).toBeNull();
	});

	it('creates a backup file when source exists', () => {
		const tmpDir = fs.mkdtempSync(path.join(require('os').tmpdir(), 'cabros-wizard-backup-'));
		const envPath = path.join(tmpDir, '.env');
		fs.writeFileSync(envPath, 'FOO=bar\n');
		try {
			const backupPath = wizard.backupEnv(envPath);
			expect(backupPath).toBeTruthy();
			expect(fs.existsSync(backupPath)).toBe(true);
			expect(fs.readFileSync(backupPath, 'utf8')).toBe('FOO=bar\n');
		} finally {
			fs.rmSync(tmpDir, { recursive: true, force: true });
		}
	});
});